<div class="home-content-box">
    <h2 class="lead">data.swissbib.ch</h2>
    <p>Die von linked.swissbib verlinkten Datenstrukturen werden via REST-Schnittstelle in verschiedenen RDF Formaten zur Verfügung gestellt.</p>
    <a href="http://swissbib.blogspot.ch/2016/07/swissbib-data-goes-linked-part-4-hydra.html" class="btn btn-link">Mehr Details</a></br>
    <a href="http://data.swissbib.ch/" class="btn btn-link">Zu data.swissbib.ch</a>
</div>