sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - VUFIND_HOME=$PWD VUFIND_LOCAL_DIR=$PWD/local

before_script:
  - pear install pear/Http_Request2
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install
  - npm install -g eslint@"<3.0.0"

cache:
  directories:
    - downloads
    - $HOME/.composer/cache

script:
  - phing composer phpunitfast phpcs-console php-cs-fixer-dryrun eslint

dist: precise
