<?
$basePath = $this->basePath();

//Item 1
$linkToAuthorDetails1 = $basePath . "/Exploration/AuthorDetails?lookfor=http://data.swissbib.ch/person/45e9b5af-bc45-36c2-9973-34e18efb6627&type=AuthorForId";
$thumbnail1 = "http://commons.wikimedia.org/wiki/Special:FilePath/Jorge_Amado,_1935.jpg";
$author1 = "Jorge Amado";
$years1 = "(1912 - 2001)";

//Item 2
$linkToAuthorDetails2 = $basePath . "/Exploration/AuthorDetails?lookfor=http://data.swissbib.ch/person/d792881e-1e3e-36df-8489-a6c3ba957e24&type=AuthorForId";
$thumbnail2 = "http://commons.wikimedia.org/wiki/Special:FilePath/CassandraAusten-JaneAusten(c.1810)_hires.jpg";
$author2 = "Jane Austen";
$years2 = "(1775 - 1817)";

//Item 3
$linkToAuthorDetails3 = $basePath . "/Exploration/AuthorDetails?lookfor=http://data.swissbib.ch/person/2b8fcc4a-c43a-3e12-8cb9-afc1c21aa6aa&type=AuthorForId";
$thumbnail3 = "http://commons.wikimedia.org/wiki/Special:FilePath/Lily_Braun.jpg";
$author3 = "Lily Braun";
$year3 = "(1865 - 1916)";

//Item 4
$linkToAuthorDetails4 = $basePath . "/Exploration/AuthorDetails?lookfor=http://data.swissbib.ch/person/aa23c630-97bd-358f-88eb-c1b4fb1fc629&type=AuthorForId";
$thumbnail4 = "http://commons.wikimedia.org/wiki/Special:FilePath/Robert_walser_1890er.jpg";
$author4 = "Robert Walser";
$year4 = "(1878 - 1956)";

//Item 5
$linkToAuthorDetails5 = $basePath . "/Exploration/AuthorDetails?lookfor=http://data.swissbib.ch/person/d633b16c-95b4-3fb3-a646-f7009c84f78b&type=AuthorForId";
$thumbnail5 = "http://commons.wikimedia.org/wiki/Special:FilePath/J._K._Rowling_2010.jpg";
$author5 = "Joanne K. Rowling";
$year5 = "(1965 - )";
?>


<div class="home-content-box">
    <h2 class="lead">AutorInnen</h2>
    <div class="lead">
        <div data-ride="carousel" class="carousel slide" id="similar-items-carousel-home-authors">

            <!-- Indicators -->
            <div class="row">
            <ol class="carousel-indicators  hidden-xs">
                <li class="active" data-slide-to="0" data-target="#similar-items-carousel-home-authors"></li>
                <li data-slide-to="1" data-target="#similar-items-carousel-home-authors"></li>
                <li data-slide-to="2" data-target="#similar-items-carousel-home-authors"></li>
                <li data-slide-to="3" data-target="#similar-items-carousel-home-authors"></li>
                <li data-slide-to="4" data-target="#similar-items-carousel-home-authors"></li>
            </ol>
            </div>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToAuthorDetails1; ?>" class="hover-overlay">
                                <img title="<? echo $author1; ?>"
                                     src="<? echo $thumbnail1; ?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $author1; ?></b>
                                <br><? echo $years1; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToAuthorDetails2; ?>" class="hover-overlay">
                                <img title="<? echo $author2; ?>"
                                     src="<? echo $thumbnail2; ?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $author2; ?></b>
                                <br><? echo $years2; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToAuthorDetails3;  ?>" class="hover-overlay">
                                <img title="<? echo $author3; ?>"
                                     src="<? echo $thumbnail3?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $author3; ?></b>
                                <br><? echo $year3; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToAuthorDetails4;  ?>" class="hover-overlay">
                                <img title="<? echo $author4; ?>"
                                     src="<? echo $thumbnail4?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $author4; ?></b>
                                <br><? echo $year4; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToAuthorDetails5;  ?>" class="hover-overlay">
                                <img title="<? echo $author5; ?>"
                                     src="<? echo $thumbnail5?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $author5; ?></b>
                                <br><? echo $year5; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control hidden-lg hidden-md hidden-sm" href="#similar-items-carousel-home-authors" data-slide="prev">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control hidden-lg hidden-md hidden-sm" href="#similar-items-carousel-home-authors" data-slide="next">
                    <span class="icon-next"></span>
                </a>

            </div>
            <!-- end class carousel-inner -->
        </div>
        <!-- end class carousel slide -->
    </div>
    <!-- end row -->
    <!--<a href="#" target="_blank" class="btn btn-link">Weiterlesen</a>-->
</div>