<?
    $basePath = $this->basePath();

    //Item 1
    $linkToInstance1 = $basePath . "/Record/440091837";
    $coverImage1 = "https://www.swissbib.ch/Cover/Show?isn=0838959687&size=medium&format=BK020000&contenttype=BK020000";
    $title1 = "Library linked data";
    $author1 = "Erik T. Mitchell";

    //Item 2
    $linkToInstance2 = $basePath . "/Record/404882447";
    $coverImage2 = "https://www.swissbib.ch/Cover/Show?isn=3499256355&size=medium&format=BK020000&contenttype=BK020000";
    $title2 = "Tschick";
    $author2 = "Wolfgang Herrndorf";

    //Item 3
    $linkToInstance3 = $basePath . "/Record/320880826";
    $coverImage3 = "https://www.swissbib.ch/Cover/Show?isn=3110278731&size=medium&format=BK020053&contenttype=BK020053";
    $title3 = "(Open) Linked Data in Bibliotheken";
    $author3 = "Patrick Danowski et al.";

    //Item 4
    $linkToInstance4 = $basePath . "/Record/121931765";
    $coverImage4 = "https://www.swissbib.ch/Cover/Show?isn=3257230451&size=medium&format=BK020000&contenttype=BK020000";
    $title4 = "Der Besuch der alten Dame";
    $author4 = "Friedrich Dürrenmatt";

    //Item 5
    $linkToInstance5 = $basePath . "/Record/371218357";
    $coverImage5 = "https://www.swissbib.ch/Cover/Show?isn=1617290394&size=medium&format=BK020053&contenttype=BK020053";
    $title5 = "Linked data: structured data on the Web";
    $author5 = " David Wood et al.";

?>

<div class="home-content-box">
    <h2 class="lead">B&uuml;cher &amp; Co.</h2>
    <div class="lead">
        <div data-ride="carousel" class="carousel slide" id="similar-items-carousel-home-works">

            <!-- Indicators -->
            <ol class="carousel-indicators  hidden-xs">
                <li class="active" data-slide-to="0" data-target="#similar-items-carousel-home-works"></li>
                <li data-slide-to="1" data-target="#similar-items-carousel-home-works"></li>
                <li data-slide-to="2" data-target="#similar-items-carousel-home-works"></li>
                <li data-slide-to="3" data-target="#similar-items-carousel-home-works"></li>
                <li data-slide-to="4" data-target="#similar-items-carousel-home-works"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToInstance1; ?>" class="hover-overlay">
                                <img title="<? echo $title1; ?>"
                                     src="<? echo $coverImage1; ?>">
                        </div>
                            <div class="col-sm-6">
                                <div class="content">
                                    <b><? echo $title1; ?></b>
                                    <br>von: <? echo $author1; ?>
                                </div>
                            </div>
                            </a>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToInstance2; ?>" class="hover-overlay">
                                <img title="<? echo $title2; ?>"
                                     src="<? echo $coverImage2?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $title2; ?></b>
                                <br>von: <? echo $author2; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToInstance3; ?>" class="hover-overlay">
                                <img title="<? echo $title3; ?>"
                                     src="<? echo $coverImage3?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $title3; ?></b>
                                <br>von: <? echo $author3; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToInstance4; ?>" class="hover-overlay">
                                <img title="<? echo $title4; ?>"
                                     src="<? echo $coverImage4?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $title4; ?></b>
                                <br>von: <? echo $author4; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-4">
                            <a href= "<? echo $linkToInstance5; ?>" class="hover-overlay">
                                <img title="<? echo $title5; ?>"
                                     src="<? echo $coverImage5?>">
                        </div>
                        <div class="col-sm-6">
                            <div class="content">
                                <b><? echo $title5; ?></b>
                                <br>von: <? echo $author5; ?>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control hidden-lg hidden-md hidden-sm" href="#similar-items-carousel-home-works" data-slide="prev">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control hidden-lg hidden-md hidden-sm" href="#similar-items-carousel-home-works" data-slide="next">
                    <span class="icon-next"></span>
                </a>

            </div>
            <!-- end class carousel-inner -->
        </div>
        <!-- end class carousel slide -->
    </div>
    <!-- end row -->
    <!--<a href="#" target="_blank" class="btn btn-link">Weiterlesen</a>-->
</div>