<style type="text/css">
    h1, h2 {
        padding-top: 20px;
    }

    ul, li {
        list-style: none;
        margin-top: 10px;
    }

    #allWrapper {
        background-color: white;
        padding-bottom: 1px;
        padding-left: 10px;
        padding-right: 25%;
    }

    #knowledgeCardAuthorWrapper {
        margin-left: 190px;
    }

    #knowledgeCardAuthorImage {
        float: left;
    }

    #knowledgeCardAuthorDescription {
        float: right;
        width: 100%;
    }

    #knowledgeCardWorks {
        clear: both;
        width: 100%;
    }

    #personJumpTo {
        margin-top: 20px;
        margin-bottom: -20px;
    }

    #personJumpTo p {
        font-size: 11px;
    }

    #personAuthorWrapper {
    }

    #personAuthorImage {
        float: left;
        margin-top: 20px;
        max-height: 162px;
        max-width: 142px;
    }

    #personAuthorDescription {
        margin-left: 170px;
    }

    #personDetailsLabel {
        float: left;
        margin-top: 50px;
        margin-left: -170px;
        font-weight: bold;
    }

    #personDetails {
        float: right;
        margin-top: 50px;
        width: 100%;
    }

    #personMoreLabels {
        float: left;
        margin-top: 20px;
        margin-left: -170px;
        font-weight: bold;
    }

    #personMoreDetails {
        float: right;
        margin-top: 20px;
        width: 100%;
    }

    #personWorks {
        clear: both;
        margin-top: 20px;
    }

    #personWorkTypes {
        clear: both;
        margin-top: 220px;
    }

    #personWorkTypes figure {
        display: inline-block;
        padding:  20px 10px 10px 0px;
        vertical-align: top;
    }

    #personWorkTypes figcaption {
        padding: 10px 10px 10px 0px;
        text-align: left;
        color: #0d785c;
        max-width: 120px;
    }

    #personTags {
        clear: both;
    }

    #personGalleries {
        clear: both;
    }

    #personGalleries figure {
        display: inline-block;
        padding: 10px;
        vertical-align: top;
    }

    #personGalleries figcaption {
        padding: 20px;
        text-align: center;
        color: #0d785c;
        max-width: 120px;
    }

    /* Sidebar */
    #personSidebar {
        position: absolute;
        top: 20px;
        left: 75%;
        float: right;
        height: 100%;
        background-color: #d3d3d3;
        padding: 15px;
    }

    #personSidebarContent {
    }

    li.externalLink {
        list-style: none;
        list-style-type: none;
        margin-left: -35px;
    }

    i.externalIcon {
    }

    i.dummyIcon {
    }

    img.externalLink {
        max-height: 16px;
        max-width: 16px;
    }

    span.externalLink {
        margin-top: -20px;
        margin-left: 22px;
        display: block;
    }


    /*Accordion*/

    #personAccordion {
        margin-top: 20px;
    }

    /*Carousel*/

    #personCarousel {
        margin-top: 10px;
    }

    #similar-items-carousel {
        float: left;
        margin-top: 10px;
        margin-right: 10px;
        margin-bottom: 20px;
        font-weight: bold;
        height: 250px;
    }

    #similar-items-carousel img {
        max-height: 200px;
    }

    /* Tabs*/

    #tabs {
        float: left;
        margin-right: 10px;
    }

    .nav-tabs > li > a:focus {
        border: 1px solid transparent;
        border-radius: 4px 4px 0 0;
        line-height: 1.42857;
        margin-right: 2px;
    }

    .nav.nav-tabs > li.ui-tabs-active > a {
        background-color: #fff;
        border-color: #ccc #ccc #fff;
        border-image: none;
        border-style: solid;
        border-width: 1px;
        color: #0d785b;
        font-weight: bold;
        margin-bottom: 0;
    }

    .tabContent {
        margin-top: 20px;
        float: left;
        background-color: #ffffff;
    }

    .tabContent img {
        margin: 20px;
    }

    .tabContentBibliographic {
        padding-left: 17%;
        margin-top: -100px;
        padding-bottom: 20px;
    }

    .tabContentText {
        padding-right: 30%;
    }

    .tabContentButtons .col-md-3{
        margin-left: 70%;
        margin-top: -125px;
    }

    .btn-primary {
        display: block;
        border-radius: 4px;
        margin-bottom: 4px;
        padding-left: 15px;
        padding-right: 15px;
        text-align: left;
        width: 173px;
        height: 35px;
    }

    .fa {
        margin-right: 2px;
    }

    #resultView:nth-child(2n+0 ) {
        background-color: #F5F5F5;
    }

    /* Tag Cloud */

    .hotag {
        width: 100%;
        padding-bottom: 20px;
        padding-right: 20px;
        float: left;
        overflow: hidden;
        text-overflow: ellipsis;
        word-spacing: 1em;
        text-align: justify;
    }
</style>
<div id="allWrapper">
    <div id="personSidebar">
        <div id="personSidebarContent">
            <div class="sidebar col-table-fix-md hidden-print resultView">
                <h4>Externe Links</h4>
                <ul id="side-panel-externalCatalogues" class="list-group">
                    <li class="list-group-item title" href="#side-collapse-externalCatalogues" data-toggle="collapse" style="background:#0d785b; color:#fff">Dieser Autor in externen Katalogen</li>
                    <div id="side-collapse-externalCatalogues" class="collapse in">
                        <a class="list-group-item facetAND" rel="external" href="http://data.bnf.fr/11905269" target="_blank">
                            <img class="externalLink" alt="" src="http://www.bnf.fr/bnf_dev/icono/favicon.ico">
                            <span class="externalLink">Bibliothèque nationale de France (Frankreich)</span>
                        </a>
                        <a class="list-group-item facetAND" rel="external" href="http://id.loc.gov/authorities/names/n79003362" target="_blank">
                            <img class="externalLink" alt="" src="http://www.loc.gov/favicon.ico">
                            <span class="externalLink">Library of Congress (USA)</span>
                        </a>
                        <a class="list-group-item facetAND" rel="external" href="https://www.deutsche-digitale-bibliothek.de/entity/118540238" target="_blank">
                            <img class="externalLink" alt="" src="../themes/linkedswissbib/images/dummyIcon.jpg">
                            <span class="externalLink">Deutsche Digitale Bibliothek (Deutschland)</span>
                        </a>
                        <a id="more-narrowGroupHidden-externalCatalogues" class="list-group-item" href="javascript:moreFacets('narrowGroupHidden-externalCatalogues')">mehr ...</a>
                            <a class="list-group-item facetAND narrowGroupHidden-externalCatalogues hidden" rel="external" href="http://data.bnf.fr/11905269" target="_blank">
                                <img class="externalLink" alt="" src="http://www.bnf.fr/bnf_dev/icono/favicon.ico">
                                <span class="externalLink">Bibliothèque nationale de France (Frankreich)</span>
                            </a>
                            <a class="list-group-item facetAND narrowGroupHidden-externalCatalogues hidden" rel="external" href="http://id.loc.gov/authorities/names/n79003362" target="_blank">
                                <img class="externalLink" alt="" src="http://www.loc.gov/favicon.ico">
                                <span class="externalLink">Library of Congress (USA)</span>
                            </a>
                        <a class="list-group-item narrowGroupHidden-externalCatalogues hidden" href="javascript:lessFacets('narrowGroupHidden-externalCatalogues')">weniger ...</a>
                    </div>
                </ul>

                <ul id="side-panel-externalLinks" class="list-group">
                    <li class="list-group-item title" href="#side-collapse-externalLinks" data-toggle="collapse" style="background:#0d785b; color:#fff" >Dieser Autor auf externen Websites</li>
                    <div id="side-collapse-externalLinks" class="collapse in">
                        <a class="list-group-item facetAND" rel="external" href="http://de.wikipedia.org/wiki/Johann_Wolfgang_von_Goethe" target="_blank">
                            <img class="externalLink" alt="" src="http://de.wikipedia.org/favicon.ico">
                            <span class="externalLink">Wikipedia (Deutsch)</span>
                        </a>
                        <a class="list-group-item facetAND" rel="external" href="http://de.wikisource.org/wiki/Johann_Wolfgang_von_Goethe" target="_blank">
                            <img class="externalLink" alt="" src="http://wikisource.org/favicon.ico">
                            <span class="externalLink">Wikisource</span>
                        </a>
                        <a class="list-group-item facetAND" rel="external" href="http://viaf.org/viaf/24602065" target="_blank">
                            <img class="externalLink" alt="" src="http://viaf.org/viaf/images/viaf.ico">
                            <span class="externalLink">VIAF - Virtual International Authority File</span>
                        </a>
                        <a id="more-narrowGroupHidden-externaLinks" class="list-group-item" href="javascript:moreFacets('narrowGroupHidden-externaLinks')">mehr ...</a>
                        <a class="list-group-item facetAND narrowGroupHidden-externaLinks hidden" rel="external" href="http://www.hls-dhs-dss.ch/textes/d/D11638.php" target="_blank">
                            <img class="externalLink" alt="" src="http://www.hls-dhs-dss.ch/favicon.ico">
                            <span class="externalLink">Historisches Lexikon der Schweiz (HLS)</span>
                        </a>
                        <a class="list-group-item narrowGroupHidden-externaLinks hidden" href="javascript:lessFacets('narrowGroupHidden-externaLinks')">weniger ...</a>
                    </div>
                </ul>


                <h4>Suche verfeinern</h4>
                <ul id="side-panel-union" class="list-group">
                    <li class="list-group-item title" href="#side-collapse-union" data-toggle="collapse"> Bibliotheksverbund </li>
                    <div id="side-collapse-union" class="collapse in">
                        <a class="list-group-item facetAND" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22IDS%22">
                            <span class="badge"> 2'742 </span>
                            Informationsverbund Deutschschweiz
                        </a>
                        <a class="list-group-item facetAND" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22IDSBB%22">
                            <span class="badge"> 1'583 </span>
                            IDS Basel Bern
                        </a>
                        <a class="list-group-item facetAND" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22NEBIS%22">
                            <span class="badge"> 1'473 </span>
                            NEBIS
                        </a>
                        <a class="list-group-item facetAND" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22RERO%22">
                            <span class="badge"> 1'049 </span>
                            RERO Réseau Romand
                        </a>
                        <a class="list-group-item facetAND" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22RE61%22">
                            <span class="badge"> 706 </span>
                            RERO Genève
                        </a>
                        <a class="list-group-item facetAND" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22SNL%22">
                            <span class="badge"> 371 </span>
                            Schweizerische Nationalbibliothek
                        </a>
                        <a id="more-narrowGroupHidden-union" class="list-group-item" href="javascript:moreFacets('narrowGroupHidden-union')">mehr ...</a>
                        <a class="list-group-item facetAND narrowGroupHidden-union hidden" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22RE81%22">
                            <a class="list-group-item facetAND narrowGroupHidden-union hidden" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22IDSLU%22">
                                <a class="list-group-item facetAND narrowGroupHidden-union hidden" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22IDSSG%22">
                                    <a class="list-group-item facetAND narrowGroupHidden-union hidden" href="/Search/Results?lookfor=malaria&type=AllFields&filter%5B%5D=union%3A%22SERVAL%22">
                                        <a class="list-group-item narrowGroupHidden-union hidden" href="javascript:lessFacets('narrowGroupHidden-union')">weniger ...</a>
                    </div>
                </ul>
            </div>
            <!-- sidebar col-table-fix-md hidden-print resultView -->
        </div>
        <!-- end persondSidebarContent -->
    </div>
    <!-- end personSidebar -->

    <?
    $results = $this->results->getResults();
    foreach ($results as $rdfDriver):
    $firstName =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getFirstName());
    $lastName =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getLastName());
    $thumbnail =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getThumbnail());
    $occupation =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getOccupation());
    $nationality =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getNationality());
    $birthDate =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getBirthDate());
    $birthPlace =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getBirthPlace());
    $deathDate =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getDeathDate());
    $deathPlace =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getDeathPlace());
    $biography = $rdfDriver->getBiography();
    $genre =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getGenre());
    $movement =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getMovement());
    $alternativeNames = preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getAlternativeNames());
    $pseudonym = preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getPseudonym());
    $influenced =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getInfluenced());
    $influencedBy =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getInfluencedBy());
    $partner =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getPartner());
    $spouse =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getSpouse());
    $notableWork =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getNotableWork());
    $source =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getSource());
    {
    ?>

    <div id="personJumpTo"><p><b>Springe zu:&nbsp;
            </b><a href="#personWorks">Werke</a>&nbsp;|&nbsp;
            <a href="#personWorkTypes">Werke als...</a>&nbsp;|&nbsp;
            <a href="#personCarousel">Werke von Zeitgenossen</a>&nbsp;|&nbsp;
            <a href="#personTags">Verwandte Themen</a>&nbsp;|&nbsp;
            <a href="#personGalleries1">Autoren mit ähnlichen Themen</a>&nbsp;|&nbsp;
            <a href="#personGalleries2">Autoren und Beitragende gemeinsamer Werke</a>
        </p>
    </div>


    <div id="personAuthorWrapper">
        <!-- <div id="personAuthorImage">
            <img src="../themes/linkedswissbib/images/JohannWolfgangVonGoethe.jpg" alt="Johann Wolfgang von Goethe">
        </div> -->
        <div id="personAuthorImage">
            <img src="<? echo $thumbnail ?>" alt="<? echo $thumbnail ?>">
        </div>
        <div id="personAuthorDescription">
<!--            <?/*
            $results = $this->results->getResults();
            if (count($results) == 1) {
                foreach ($results as $rdfDriver): */?>
                    <div>
                        <h2>
                            <?/*=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getFirstNameContributor()); */?>
                            <?/*=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getLastNameContributor()); */?>
                        </h2>
                    </div>
                <?/*endforeach;
            } else { */?>
                <div id="resultView">
                    <h2>Johann Wolfgang von Goethe</h2>
                </div>
            --><?/* }; */?>


            <h2><?echo $firstName . " " . $lastName ?></h2>
            <!-- Schriftsteller, Publizist, Politiker, Jurist, Naturwissenschaftler, Theaterintendant, Maler, Zeichner<br /><br /> -->
            <p><?echo $occupation?></p>
            <p><b>Geboren:</b> <?echo $birthDate . ", " . $birthPlace?><br />
               <b>Gestorben:</b> <?echo $deathDate . ", " . $deathPlace?><br />
                <!-- Geboren: 28. August 1749, Frankfurt am Main<br />
                Gestorben; 22. März 1832, Weimar -->
               <b>Nationalität:</b> <? echo $nationality?><br>
            </p>

            <div id="personAccordion">
                <div aria-multiselectable="true" role="tablist" id="accordion" class="panel-group">
                    <div id="holdings-details" class="panel panel-default">
                        <div id="heading-details" role="tab" class="panel-heading">
                            <h3 class="panel-title">
                                <a  aria-expanded="false" href="#collapse-details" data-toggle="collapse">
                                    <span>Mehr Details zu <? echo $firstName." ".$lastName ?></span>
                                </a>
                            </h3>
                        </div>

                        <div aria-labelledby="heading-details" role="tabpanel" class="panel-collapse collapse" level="1" id="collapse-details">
                            <div class="list-group">
                                    <div id="personDetailsLabel">Biografie:</div>
                                    <div id="personDetails"><?echo $biography?><!--Johann Wolfgang von Goethe (* 28. August 1749 in Frankfurt am Main als Johann Wolfgang Goethe; † 22. März 1832 in Weimar), geadelt 1782,
                                                    gilt als einer der bedeutendsten Repräsentanten deutschsprachiger Dichtung. Goethe stammte aus einer angesehenen bürgerlichen Familie; sein Grossvater
                                                    mütterlicherseits war als Stadtschultheiss höchster Beamter der Stadt Frankfurt, sein Vater Doktor der Rechte und kaiserlicher Rat. Er und seine Schwester Cornelia
                                                    erfuhren eine aufwendige Ausbildung durch Hauslehrer. Dem Wunsch seines Vaters folgend studierte Goethe in Strassburg und Leipzig Rechtswissenschaft und war danach
                                                    als Advokat in Wetzlar und Frankfurt tätig. Gleichzeitig drängten ihn Talent und Neigung zur Dichtkunst, die ihm mit dem Drama Götz von Berlichingen einen frühen
                                                    Erfolg und Anerkennung in der literarischen Welt zuteilwerden liess. --></div>
                                    <div id="personMoreDetails"><?echo $notableWork?><!--Drama, Deutsche Literatur, Schauspiel, Gedichte --></div>
                                    <div id="personMoreLabels">Wichtigste Werke <br /> (Notable Work):</div>
                                    <div id="personMoreDetails"><?echo $genre?><!--Drama, Deutsche Literatur, Schauspiel, Gedichte --></div>
                                    <div id="personMoreLabels">Genre/Kategorie <br /> (Genre):</div>
                                    <div id="personMoreDetails"><?echo $movement?><!-- wilhelminische Ära, Romantik, Aufklärung --></div>
                                    <div id="personMoreLabels">Bewegung, Zeit, Ära <br /> (Movement):</div>
                                    <div id="personMoreDetails"> <? echo $alternativeNames?>
                                                    <!-- Johann Wolfgang von Göthe<br />
                                                    Wolfgang von Goethe<br />
                                                    Wolfgang Goethe<br />
                                                    Johann Wolfgang Goethe--></div>
                                    <div id="personMoreLabels">Namensvarianten:</div>
                                    <div id="personMoreDetails"> <? echo $pseudonym?></div>
                                    <div id="personMoreLabels">Pseudonyme:</div>
                                    <div id="personMoreDetails">
                                                    <?echo $partner . " (Partner/s)<br>" .
                                                           $spouse  . " (Spouse/s)<br>" .
                                                           $influenced . " (influenced)<br>" .
                                                           $influencedBy . " (influencedBy)<br>" ?>
                                                    <!-- Elisabeth Goethe (Mutter)<br />
                                                    Friedel Knolle (berufliche Beziehung)<br />
                                                    Rolf Alpers (berufliche Beziehung)<br />
                                                    Hermann Heinzel (berufliche Beziehung)<br /> --></div>
                                    <div id="personMoreLabels">In Beziehung <br></b>stehend:</div>
                                    <div id="personMoreDetails"><? echo $source?>
                                        <!-- VIAF - Virtual International Authority File<br />
                                                    Wikipedia (Deutsch)<br /> --></div>
                                    <div id="personMoreLabels">Quellen:</div>
                            </div>
                            <!-- end list-group -->
                        </div>
                        <!-- end collapse-details -->
                    </div>
                    <!-- end holding-details -->
                </div>
                <!-- end accordion -->
             </div>
            <!-- end personAccordion -->
        </div>
        <!-- end personAuthorDescription -->
        <?
        }
        endforeach;
        ?>
    </div>
    <!-- end personAuthorWrapper -->

    <div id="personWorks">
        <h4>Werke</h4>
        <div id="tabs">
            <ul class="recordTabs nav nav-tabs">
                <li><a href="#tabs-1">Alles</a></li>
                <li><a href="#tabs-2">Beteiligt an</a></li>
                <li><a href="#tabs-3">Thema in</a></li>
            </ul>

            <div id="tabs-1">
                <div class="tabContent">
                    <?
                    $results = $this->results->getResults();
                    foreach ($results as $rdfDriver):
                        $title =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getTitle());
                        /* $title = $title;
                        $subtitle = "the writer";*/
                        $statementOfResponsibility =  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getStatementOfResponsibility());
                        $author = preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getName());
                        $year = preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getPublicationStatement());
                        $format = preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getRdfType());;
                        $coverImage = preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getISBN10());
                        $numberOfInstitutions = "2 Bibliotheken";
                        $holdingInstitution = "ETH Zürich - Bibliothek HDB";
                        $linkToHoldings = "#";

                        {
                            ?>
                            <div id="resultView">
                                <img src=<?echo $coverImage?> alt="Goethe">
                                <div class="tabContentBibliographic">
                                    <div class="tabContentText">
                                    <h4><?echo $title?></h4>
                                    <p><?echo $statementOfResponsibility ?></p>
                                    <p>
                                        <?echo $subtitle?><br />
                                        <b>Verfasser/Beitragende:&nbsp;</b><? echo $author ?><br />
                                        <b>Jahr:&nbsp;</b><?echo $year?><br />
                                        <b>Format:&nbsp;</b><?echo $format?>
                                    </p>
                                    </div>
                                    <div class="tabContentButtons">
                                        <div class="col-md-3 actions">
                                            <a id="dropdownLibraries" class="btn btn-primary dropdown-toggle hidden-print" data-toggle="dropdown">
                                        <span>
                                        <i class="fa fa-institution"></i>
                                        </span>
                                                <span class="hidden-xs hidden-sm"><?echo $numberOfInstitutions?></span>
                                            </a>
                                    <span class="visible-print-inline">
                                    <i class="fa fa-institution"></i>
                                    </span>
                                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownLibraries" role="menu">
                                                <li role="presentation">
                                                    <a href="<?echo $linkToHoldings?>" role="menuitem">
                                                        <span class="a-before"></span>
                                                        <?echo $holdingInstitution ?>
                                                    </a>
                                                </li>
                                                <li role="presentation">
                                                    <a href="<?echo $linkToHoldings?>" role="menuitem">
                                                        <span class="a-before"></span>
                                                        <?echo $holdingInstitution ?>
                                                    </a>
                                                </li>
                                            </ul>
                                            <a class="btn btn-primary btn-frbr hidden-print" title="Weitere Ausgaben" href="#">
                                        <span>
                                        <i class="fa fa-eye"></i>
                                        </span>
                                                <span class="hidden-xs hidden-sm">Weitere Ausgaben</span>
                                            </a>
                                            <a class="btn btn-primary hidden-print" title="Zu Merkliste hinzufügen" href="#">
                                        <span class="memorizelistadd">
                                        <i class="fa fa-list-ul"></i>
                                        </span>
                                                <span class="hidden-xs hidden-sm">Merkliste</span>
                                            </a>
                                            <div class="savedLists alert alert-info hidden hidden-xs hidden-sm hidden-print">
                                                <strong>Gespeichert in:</strong>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?
                        }
                    endforeach;
                    ?>
                </div>
                <!-- end tabContent -->
            </div>
            <!-- end tabs-1 -->


            <div id="tabs-2">
                <div class="tabContent">
                    <?
                    $title = "Goethe";
                    $subtitle = "the poet";
                    $author = "Rüdiger Safranski";
                    $year = "2014";
                    $format = "Buch";
                    $coverImage = "../themes/linkedswissbib/images/Goethe_Safranski.jpg";
                    $numberOfInstitutions = "2 Bibliotheken";
                    $holdingInstitution = "ETH Zürich - Bibliothek HDB";
                    $linkToHoldings = "#";

                    for ($i = 0; $i <= 2; $i++) {
                        ?>
                        <div id="resultView">
                            <img src=<?echo $coverImage?> alt="Goethe">
                            <div class="tabContentBibliographic">
                                <h4><?echo $title?></h4>
                                <p>
                                    <?echo $subtitle?><br />
                                    <b>Verfasser/Beitragende:&nbsp;</b><?echo $author?><br />
                                    <b>Jahr:&nbsp;</b><?echo $year?><br />
                                    <b>Format:&nbsp;</b><?echo $format?>
                                </p>
                                <div class="tabContentButtons">
                                    <div class="col-md-3 actions">
                                        <a id="dropdownLibraries" class="btn btn-primary dropdown-toggle hidden-print" data-toggle="dropdown">
                                        <span>
                                        <i class="fa fa-institution"></i>
                                        </span>
                                            <span class="hidden-xs hidden-sm"><?echo $numberOfInstitutions?></span>
                                        </a>
                                    <span class="visible-print-inline">
                                    <i class="fa fa-institution"></i>
                                    </span>
                                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownLibraries" role="menu">
                                            <li role="presentation">
                                                <a href="<?echo $linkToHoldings?>" role="menuitem">
                                                    <span class="a-before"></span>
                                                    <?echo $holdingInstitution ?>
                                                </a>
                                            </li>
                                            <li role="presentation">
                                                <a href="<?echo $linkToHoldings?>" role="menuitem">
                                                    <span class="a-before"></span>
                                                    <?echo $holdingInstitution ?>
                                                </a>
                                            </li>
                                        </ul>
                                        <a class="btn btn-primary btn-frbr hidden-print" title="Weitere Ausgaben" href="#">
                                        <span>
                                        <i class="fa fa-eye"></i>
                                        </span>
                                            <span class="hidden-xs hidden-sm">Weitere Ausgaben</span>
                                        </a>
                                        <a class="btn btn-primary hidden-print" title="Zu Merkliste hinzufügen" href="#">
                                        <span class="memorizelistadd">
                                        <i class="fa fa-list-ul"></i>
                                        </span>
                                            <span class="hidden-xs hidden-sm">Merkliste</span>
                                        </a>
                                        <div class="savedLists alert alert-info hidden hidden-xs hidden-sm hidden-print">
                                            <strong>Gespeichert in:</strong>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?
                    }
                    ?>
                </div>
                <!-- end tabContent -->
            </div>
            <!-- end tabs-2 -->

            <div id="tabs-3">
                <div class="tabContent">
                    <?
                    $title = "Goethe";
                    $subtitle = "the German";
                    $author = "Norbert Mecklenburg";
                    $year = "2014";
                    $format = "Buch";
                    $coverImage = "../themes/linkedswissbib/images/Goethe_Mecklenburg.jpg";
                    $numberOfInstitutions = "2 Bibliotheken";
                    $holdingInstitution = "ETH Zürich - Bibliothek HDB";
                    $linkToHoldings = "#";

                    for ($i = 0; $i <= 2; $i++) {
                        ?>
                        <div id="resultView">
                            <img src=<?echo $coverImage?> alt="Goethe">
                            <div class="tabContentBibliographic">
                                <h4><?echo $title?></h4>
                                <p>
                                    <?echo $subtitle?><br />
                                    <b>Verfasser/Beitragende:&nbsp;</b><?echo $author?><br />
                                    <b>Jahr:&nbsp;</b><?echo $year?><br />
                                    <b>Format:&nbsp;</b><?echo $format?>
                                </p>
                                <div class="tabContentButtons">
                                    <div class="col-md-3 actions">
                                        <a id="dropdownLibraries" class="btn btn-primary dropdown-toggle hidden-print" data-toggle="dropdown">
                                        <span>
                                        <i class="fa fa-institution"></i>
                                        </span>
                                            <span class="hidden-xs hidden-sm"><?echo $numberOfInstitutions?></span>
                                        </a>
                                    <span class="visible-print-inline">
                                    <i class="fa fa-institution"></i>
                                    </span>
                                        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownLibraries" role="menu">
                                            <li role="presentation">
                                                <a href="<?echo $linkToHoldings?>" role="menuitem">
                                                    <span class="a-before"></span>
                                                    <?echo $holdingInstitution ?>
                                                </a>
                                            </li>
                                            <li role="presentation">
                                                <a href="<?echo $linkToHoldings?>" role="menuitem">
                                                    <span class="a-before"></span>
                                                    <?echo $holdingInstitution ?>
                                                </a>
                                            </li>
                                        </ul>
                                        <a class="btn btn-primary btn-frbr hidden-print" title="Weitere Ausgaben" href="#">
                                        <span>
                                        <i class="fa fa-eye"></i>
                                        </span>
                                            <span class="hidden-xs hidden-sm">Weitere Ausgaben</span>
                                        </a>
                                        <a class="btn btn-primary hidden-print" title="Zu Merkliste hinzufügen" href="#">
                                        <span class="memorizelistadd">
                                        <i class="fa fa-list-ul"></i>
                                        </span>
                                            <span class="hidden-xs hidden-sm">Merkliste</span>
                                        </a>
                                        <div class="savedLists alert alert-info hidden hidden-xs hidden-sm hidden-print">
                                            <strong>Gespeichert in:</strong>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?
                    }
                    ?>
                </div>
            <!-- end tabContent -->
            </div>
            <!-- end tabs-3 -->
        </div>
        <!-- end tabs -->
        <script>
            $(function() {
                $( "#tabs" ).tabs();
            });
        </script>
    </div>
    <!-- end personWorks -->

    <div id="personWorkTypes">
        <h4>Werke als...</h4>
        <figure>
            <img src="../themes/linkedswissbib/images/icon_hoerbuch.jpg" alt="Hörbuch">
            <figcaption>Hörbuch / Tonaufnahme (5'601)</figcaption>
        </figure>
        <figure>
            <img src="../themes/linkedswissbib/images/icon_noten.jpg" alt="Noten">
            <figcaption>Noten (Partitur) (650)</figcaption>
        </figure>
        <figure>
            <img src="../themes/linkedswissbib/images/icon_eBook.jpg" alt="eBook">
            <figcaption>eBook (1'256)</figcaption>
        </figure>
        <figure>
            <img src="../themes/linkedswissbib/images/icon_buch.jpg" alt="Buch">
            <figcaption>gedrucktes Buch (34'455)</figcaption>
        </figure>
        <figure>
            <img src="../themes/linkedswissbib/images/icon_video.jpg" alt="video">
            <figcaption>Film / Video (4'756)</figcaption>
        </figure>
    </div>

    <div id="personCarousel">
        <h4>Werke von Zeitgenossen</h4>

        <div data-ride="carousel" class="carousel slide" id="similar-items-carousel">

            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li class="active" data-slide-to="0" data-target="#similar-items-carousel"></li>
                <li data-slide-to="1" data-target="#similar-items-carousel"></li>
                <li data-slide-to="2" data-target="#similar-items-carousel"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <div class="row">
                        <div class="col-sm-3">
                            <a href="/Record/32887101X" class="hover-overlay" style="min-height: 200px;">
                                <img title="Until you make the shore" src="https://resources.swissbib.ch/Cover/Show?isn=1908836679&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Until you make the shore</b>
                                    <br>von: Conaway, Cameron
                                    <br>Veröffentlicht: 2014
                                </div>
                            </a>
                        </div>

                        <div class="col-sm-3">
                            <a href="/Record/175208727" class="hover-overlay" style="min-height: 200px;">
                                <img title="Incarnadine : poems" src="https://resources.swissbib.ch/Cover/Show?isn=1555976352&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Incarnadine : poems</b>
                                    <br>von: Szybist, Mary
                                    <br>Veröffentlicht: 2013
                                </div>
                            </a>

                        </div>
                        <div class="col-sm-3">
                            <a href="/Record/176525807" class="hover-overlay" style="min-height: 200px;">
                                <img title="Sightline : poems" src="https://resources.swissbib.ch/Cover/Show?isn=0976640554&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Sightline : poems</b>
                                    <br>von: Austen, Elizabeth
                                    <br>Veröffentlicht: 2010</div>
                            </a>
                        </div>
                        <div class="col-sm-3">
                            <a href="/Record/314280111" class="hover-overlay" style="min-height: 200px">
                                <img title="Start with a small guitar : poems" src="https://resources.swissbib.ch/Cover/Show?isn=0988924838&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Start with a small guitar : poems</b>
                                    <br>von: Thompson, Lynne
                                    <br>Veröffentlicht: 2013
                                </div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-3">
                            <a href="/Record/327412496" class="hover-overlay" style="min-height: 200px;">
                                <img title="Copia : poems" src="https://resources.swissbib.ch/Cover/Show?isn=1938160460&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Copia : poems</b>
                                    <br>von: Meitner, Erika
                                    <br>Veröffentlicht: 2014
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-3">
                            <a href="/Record/304901997" class="hover-overlay" style="min-height: 200px;">
                                <img title="Embark : poems" src="https://resources.swissbib.ch/Cover/Show?isn=0976640570&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Embark : poems</b>
                                    <br>Veröffentlicht: 2012
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-3">
                            <a href="/Record/307411990" class="hover-overlay" style="min-height: 200px;">
                                <img title="Collected poems" src="https://resources.swissbib.ch/Cover/Show?isn=1598530836&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Collected poems</b>
                                    <br>von: Cullen, Countee
                                    <br>Veröffentlicht: 2013
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-3">
                            <a href="/Record/331150034" class="hover-overlay" style="min-height: 200px;">
                                <img title="Streaming : poems" src="https://resources.swissbib.ch/Cover/Show?isn=1566893755&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Streaming : poems</b>
                                    <br>von: Coke, Allison Adelle Hedge
                                    <br>Veröffentlicht: 2014
                                </div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="item">
                    <div class="row">
                        <div class="col-sm-3">
                            <a href="/Record/335357466" class="hover-overlay" style="min-height: 200px;">
                                <img title="Selfish : poems" src="https://resources.swissbib.ch/Cover/Show?isn=1555977081&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Selfish : poems</b>
                                    <br>von: Goldbarth, Albert
                                    <br>Veröffentlicht: 2015
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-3">
                            <a href="/Record/182619362" class="hover-overlay" style="min-height: 200px;">
                                <img title="Rumors of Earth : poems" src="https://resources.swissbib.ch/Cover/Show?isn=1890193348&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Rumors of Earth : poems</b>
                                    <br>von: Edwards, Robert
                                    <br>Veröffentlicht: 2011
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-3">
                            <a href="/Record/318749041" class="hover-overlay" style="min-height: 200px;">
                                <img title="The earth avails : poems" src="https://resources.swissbib.ch/Cover/Show?isn=1555976662&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>The earth avails : poems</b>
                                    <br>von: Wunderlich, Mark
                                    <br>Veröffentlicht: 2014
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-3">
                            <a href="/Record/185321690" class="hover-overlay" style="min-height: 200px;">
                                <img title="Must a violence : poems" src="https://resources.swissbib.ch/Cover/Show?isn=1609381297&amp;size=large" style="max-height: 200px;">
                                <div class="content">
                                    <i title="Buch" class="fa fa-x fa-buch"></i>
                                    <b>Must a violence : poems</b>
                                    <br>von: Buchanan, Oni
                                    <br>Veröffentlicht: 2012
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end class carousel-inner -->
            <!-- Controls -->
            <a data-slide="prev" role="button" href="#similar-items-carousel" class="left carousel-control">
                <span class="fa fa-chevron-left glyphicon-chevron-left"></span>
            </a>
            <a data-slide="next" role="button" href="#similar-items-carousel" class="right carousel-control">
                <span class="fa fa-chevron-right glyphicon-chevron-right"></span>
            </a>

        </div>
        <!-- end class carousel slide -->
    </div>

    <div id="personTags">
         <h4>Verwandte Themen</h4>
        <!--<figure>
            <img src="../themes/linkedswissbib/images/Tagcloud.jpg" alt="Tagcloud">
        </figure>-->
        <div id="main" class="hotag">
        </div>

        <!-- Link causes problems if placed at page's head -->
        <script src="../themes/linkedswissbib/js/jquery.hotag.js"></script>
        <script>
            var tags = [{"counts":2,"tag":"Dies","href":"#"},
                {"counts":1,"tag":"ist","href":"#"},
                {"counts":1,"tag":"eine","href":"#"},
                {"counts":5,"tag":"Tag Cloud","href":"#"},
                {"counts":2,"tag":"und","href":"#"},
                {"counts":1,"tag":"zeigt","href":"#"},
                {"counts":2,"tag":"verwandte","href":"#"},
                {"counts":5,"tag":"Themen","href":"#"},
                {"counts":1,"tag":"das","href":"#"},
                {"counts":2,"tag":"heisst","href":"#"},
                {"counts":6,"tag":"Schlagworte","href":"#"},
                {"counts":1,"tag":"welche","href":"#"},
                {"counts":1,"tag":"mit","href":"#"},
                {"counts":4,"tag":"der Person","href":"#"},
                {"counts":1,"tag":"beziehungsweise","href":"#"},
                {"counts":5,"tag":"deren Werke", "href":"#"},
                {"counts":3,"tag":"in Verbindung stehen","href":"#"}
            ];

            $("#main").hotag({
                tags: tags,
                containerClass: 'hotag'
            });
        </script>
    </div>

    <div id="personGalleries1">
        <div id="personGalleries">
            <h4>Autoren mit ähnlichen Themen</h4>
            <figure>
                <img src="../themes/linkedswissbib/images/FriedrichSchiller.jpg" alt="Friedrich Schiller">
                <figcaption>Friedrich Schiller</figcaption>
            </figure>
            <figure>
                <img src="../themes/linkedswissbib/images/HeinrichHeine.jpg" alt="Heinrich Heine">
                <figcaption>Heinrich Heine</figcaption>
            </figure>
            <figure>
                <img src="../themes/linkedswissbib/images/FriedrichNietzsche.jpg" alt="Friedrich Nietzsche">
                <figcaption>Friedrich Nietzsche</figcaption>
            </figure>
            <figure>
                <img src="../themes/linkedswissbib/images/GottholdEphraimLessing.jpg" alt="Gotthold Ephraim Lessing">
                <figcaption>Gotthold Ephraim Lessing</figcaption>
            </figure>
            <figure>
                <img src="../themes/linkedswissbib/images/ImmanuelKant.jpg" alt="Immanuel Kant">
                <figcaption>Immanuel Kant</figcaption>
            </figure>
        </div>
    </div>

    <div id="personGalleries2">
        <div id="personGalleries">
            <h4>Autoren und Beitragende gemeinsamer Werke</h4>
            <figure>
                <img src="../themes/linkedswissbib/images/ThomasMann.jpg" alt="Thomas Mann">
                <figcaption>Thomas Mann</figcaption>
            </figure>
            <figure>
                <img src="../themes/linkedswissbib/images/FriedrichSchiller.jpg" alt="Friedrich Schiller">
                <figcaption>Friedrich Schiller</figcaption>
            </figure>
            <figure>
                <img src="../themes/linkedswissbib/images/ImmanuelKant.jpg" alt="Immanuel Kant">
                <figcaption>Immanuel Kant</figcaption>
            </figure>
        </div>
    </div>
</div>
<!-- end AllWrapper -->