<div role="main" class="main">
    <?
    $instances = array();

    $results = $this->results->getResults();
    foreach ($results as $singleResult):
        if ($singleResult->isPerson()) {
            $person_uniqueId = $singleResult->getUniqueID();
            $person_alternativeNames = $singleResult->getAlternativeNames();
            $person_biography = $singleResult->getBiography();
            $person_birthDate = $singleResult->getBirthDate();
            $person_birthPlace = $singleResult->getBirthPlace();
            $person_deathDate = $singleResult->getDeathDate();
            $person_deathPlace = $singleResult->getDeathPlace();
            $person_genre = $singleResult->getGenre();
            $person_influenced = $singleResult->getInfluenced();
            $person_influencedBy = $singleResult->getInfluencedBy();
            $person_movement = $singleResult->getMovement();
            $person_nameAsLabel = $singleResult->getNameAsLabel();
            $person_nationality = $singleResult->getNationality();
            $person_notableWork = $singleResult->getNotableWork();
            $person_occupation = $singleResult->getOccupation();
            $person_partner = $singleResult->getPartner();
            $person_pseudonym = $singleResult->getPseudonym();
            $person_spouse = $singleResult->getSpouse();
            $person_source = $singleResult->getSource();
            $person_thumbnail = $singleResult->getThumbnail();
        } else
            $instances[] = $singleResult;
    endforeach;
    ?>
    <div class="container container-table-fix-md breadcrumbWrapper">
        <ul class="breadcrumb hidden-print">

            <li>
                <a href="/sbrd/Exploration/AuthorDetailsResponsive?lookfor=<? echo $person_uniqueId ?>&amp;type=Contributor">Suche</a>
            </li>
            <!-- Example from swissbib classic
                <a href="/Search/Results?lookfor=malaria&type=AllFields">Suche: malaria</a>
            -->
            <li class="active"><a
                    href="/sbrd/Exploration/AuthorDetailsResponsive?lookfor=<? echo $person_uniqueId ?>&amp;type=Contributor"><? echo $person_uniqueId ?></a>
            </li>
            <li class="active">Personenseite</li>
            <?

            ?>
        </ul>
    </div>
    <!-- end class container container-table-fix-md breadcrumbWrapper -->
    <div class="container container-table-fix-md">
        <div class="row row-table-fix-md table-sidebar">
            <div class="col-md-12 col-table-fix-md dirty-hack-column">
                <div class="row bg-grey">
                    <div class="col-md-9 col-table-fix-md resultView bg-white">
                        <div class="results-top row">
                            <div class="col-md-9">
                                <!-- search results incl. icon
                                    <h1><i class="fa fa-search"></i> <span>Suchergebnisse</span></h1>
                                    <h2 class="visible-print-block">Ihre Suche: <span>malaria, 4048 Treffer</span></h2>
                                -->
                                <b>Springe zu:&nbsp;</b>
                                <a href="#works">Werke</a>&nbsp;|&nbsp;
                                <a href="#mediaType">Medientyp</a>&nbsp;|&nbsp;
                                <a href="#worksOfContemporaries">Werke von Zeitgenossen</a>&nbsp;|&nbsp;
                                <a href="#relatedTopics">Verwandte Themen</a>&nbsp;|&nbsp;
                                <a href="#authorsWithSimilarTopics">Autoren mit ähnlichen Themen</a>&nbsp;|&nbsp;
                                <a href="#authorsOfCommonWorks">Autoren und Beitragende gemeinsamer Werke</a>
                            </div>
                            <!-- end class col-md-9 -->
                            <div class="col-md-3">
                                <!-- icons export, save etc. -->
                                <div class="searchtools">
                                    <div class="searchtools hidden-print">
                                        <!-- #TODO: Replace static links -->
                                        <a href="?lookfor=malaria&amp;type=AllFields&amp;view=rss"
                                           title="Neue Einträge zu dieser Suche per Feed gemeldet bekommen"><i
                                                class="fa fa-rss"></i></a>
                                        <a href="/Search/Email" id="mailSearch29097239" title="Per E-Mail versenden"><i
                                                class="fa fa-envelope"></i></a>
                                        <a href="/MyResearch/SaveSearch?save=29097239" title="Suche speichern"><i
                                                class="fa fa-plus-square"></i></a>
                                        <!-- Styling & Funktionstests -->
                                        <a class="export-toggle dropdown-toggle hidden-xs hidden-sm"
                                           data-toggle="dropdown" href="/Record//Export" title=" Exportieren"><i
                                                class="fa fa-share"></i></a>
                                        <ul class="dropdown-menu" role="export-menu">
                                            <li class="visible-md visible-lg">
                                                <a href="https://www.swissbib.ch/Cart/doExport?f=EndNote">Exportieren
                                                    nach EndNote</a>
                                            </li>
                                            <li class="visible-md visible-lg">
                                                <a href="https://www.swissbib.ch/Cart/doExport?f=BibTeX">Exportieren
                                                    nach BibTeX</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <!-- end class searchtools hidden-print -->
                                </div>
                                <!-- end class searchtools -->
                            </div>
                            <!-- end class col-md-3 -->
                        </div>
                        <!-- end class results-top row -->
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-2">
                                    <h2></h2>
                                    <img class="img-responsive" src="<? echo $person_thumbnail ?>"
                                         alt="<? echo $person_thumbnail ?>">
                                </div>
                                <div class="col-sm-10">
                                    <div class="meta">
                                        <h2>
                                            <? echo $person_nameAsLabel ?>
                                        </h2>
                                    </div>
                                    <!-- occupation -->
                                    <div class="meta">
                                        <p><? echo $person_occupation ?></p>
                                    </div>
                                    <!-- birthdate, birthplace -->
                                    <div class="meta">
                                        <span><strong>Geboren: </strong></span><span><? echo $person_birthDate . " " . $person_birthPlace ?></span><br>
                                    </div>
                                    <!-- deathdate, deathplace -->
                                    <div class="meta">
                                        <span><strong>Gestorben: </strong></span><span><? echo $person_deathDate . " " . $person_deathPlace ?></span><br>
                                    </div>
                                    <!-- deathdate, deathplace -->
                                    <div class="meta">
                                        <span><strong>Nationalität: </strong></span><span><? echo $person_nationality ?></span><br><br>
                                    </div>
                                    <div id="accordion" class="panel-group" aria-multiselectable="true"
                                         role="tablist">
                                        <div id="holdings-details" class="panel panel-default">
                                            <div id="heading-details" class="panel-heading" role="tab">
                                                <h3 class="panel-title">
                                                    <a aria-expanded="false" href="#collapse-details"
                                                       data-toggle="collapse">
                                                        <span>Mehr Details zu <? echo $person_nameAsLabel ?></span>
                                                    </a>
                                                </h3>
                                            </div>
                                            <!-- end class panel-heading -->
                                        </div>
                                        <!-- end id holdings-details -->
                                    </div>
                                    <!-- end id accordion -->
                                </div>
                                <!-- end class col-sm-10 -->
                            </div>
                            <!-- end class row -->
                            <div id="collapse-details" class="panel-collapse collapse"
                                 aria-labelledby="heading-details" role="tabpanel" level="1">
                                <dl>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Biografie:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_biography ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Wichtigste Werke:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_notableWork ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Genre:</dt>
                                        <dd class="col-sm-10"><? echo $person_genre ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Bewegung, Zeit, Ära (Movement):</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_movement ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Namens-<br>varianten:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_alternativeNames ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Pseudonyme:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_pseudonym ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>In Beziehung stehend:</p></dt>
                                        <dd class="col-sm-10">
                                            <p>
                                                <? echo
                                                    $person_partner . " (Partner/s)<br>" .
                                                    $person_spouse . " (Spouse/s)<br>" .
                                                    $person_influenced . " (influenced)<br>" .
                                                    $person_influencedBy . " (influencedBy)<br>"
                                                ?>
                                            </p>
                                        </dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Quellen:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_source ?></p></dd>
                                    </div>
                                </dl>
                            </div>
                            <!-- end id collapse-more -->
                        </div>
                        <!-- end class container-fluid -->
                    </div>
                    <!-- end class col-md-9 col-table-fix-md resultView bg-white -->
                </div>
                <!-- end class row bg-grey -->
            </div>
            <!-- end class col-md-12 col-table-fix-md dirty-hack-column -->
        </div>
        <!-- end class row row-table-fix-md table-sidebar -->
    </div>
    <!-- container container-table-fix-md -->
    <div id="bottom-puffer"></div>
</div>
<!-- end class main -->
