
<p>&nbsp;</p>
<h2>Judith Kuckart (1959 - )</h2>
<div id="authorImage">
<img src="../themes/linkedswissbib/images/JudithKuckart.jpg" alt="Judith Kuckart">
</div>
<div id="authorDescription">
Schriftstellerin, Theaterregisseurin
<p>Geboren: 17. Juni 1959, Schwelm<br />
-
</p>
<p><b>Schlagworte/Themen</b><br />
Jugend | Schule | Verschwinden<br />
Mehr...
</p>
</div>
<div id="works">
<p><b>Werke</b></p>
<p>
    <img src="../themes/linkedswissbib/images/JudithKuckart_DerBibliothekar.jpg" alt="Der Bibliothekar">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_DieVerdächtige.jpg" alt="Die Verdächtige">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_Kaiserstrasse.jpg" alt="Kaiserstrasse">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_LenasLiebe.jpg" alt="Lenas Liebe">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_WahlDerWaffen.jpg" alt="Wahl der Waffen">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_Wuensche.jpg" alt="Wuensche">&nbsp;<br />
</p>
<p><b>Werke finden in...</b><br />
allen Katalogen | NEBIS | IDS Basel Bern | ID Luzern | RERO | Alexandria
</p>
</div>

<?
    $results = $this->results->getResults();
    foreach ($results as $rdfDriver): ?>
        <div>
            <a href="<?= $rdfDriver->getUniqueID()?>">document-IRI</a>
        </div>
        <div>
            <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getRdf()); ?>
        </div>
            <div>&nbsp;</div>
    <?endforeach;?>

<p>&nbsp;</p>
