<div id="allWrapper">
<h2>Judith Kuckart (1959 - )</h2>
<div id="authorWrapper">
<div id="authorImage">
<img src="../themes/linkedswissbib/images/JudithKuckart.jpg" alt="Judith Kuckart">
</div>
<div id="authorDescription">
Schriftstellerin, Theaterregisseurin
<p>Geboren: 17. Juni 1959, Schwelm<br />
-
</p>
<p><b>Schlagworte/Themen</b><br />
Jugend | Schule | Verschwinden<br />
Mehr...
</p>
</div>
</div>
<div id="works">
<p><h2>Werke</h2></p>
<p>
    <img src="../themes/linkedswissbib/images/JudithKuckart_DerBibliothekar.jpg" alt="Der Bibliothekar">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_DieVerdächtige.jpg" alt="Die Verdächtige">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_Kaiserstrasse.jpg" alt="Kaiserstrasse">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_LenasLiebe.jpg" alt="Lenas Liebe">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_WahlDerWaffen.jpg" alt="Wahl der Waffen">&nbsp;
    <img src="../themes/linkedswissbib/images/JudithKuckart_Wuensche.jpg" alt="Wuensche">&nbsp;<br />
</p>
<p><h2>Werke finden in...</h2><br />
allen Katalogen | NEBIS | IDS Basel Bern | ID Luzern | RERO | Alexandria
</p>
</div>
        <?
        $results = $this->results->getResults();
        foreach ($results as $rdfDriver): ?>
        <div id="resultView">
            <p>
                <h4><?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getTitle()); ?></h4>
                <b>Verfasser, Beitragende:</b> &nbsp;<?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getFirstNameResources()); ?>
                <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getLastNameResources()); ?><br />
                <b>Ort, Verlag, Jahr:</b> &nbsp; <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getPublicationStatement()); ?><br />
                <b>Beschreibung:</b> &nbsp; <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getFormat()); ?><br />
                <b>Link Cover (ID):</b> &nbsp; <a rel="external" href="<?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getCover()); ?>">
                <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getCover()); ?></a><br />
                <b>Link Cover (ISBN10):</b> &nbsp; <a rel="external" href="<?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getISBN10()); ?>">
                <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getISBN10()); ?></a><br />
                <img src="<?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getISBN10()); ?>">
            </p>
            <br />
        </div>
    <? endforeach;?>
<p>&nbsp;</p>
</div>
