<div role="main" class="main">
    <script src="../themes/linkedswissbib/js/authordetails.js"></script>
    <script src="../themes/linkedswissbib/js/detailspages.js"></script>
    <?
    $instances = array();
    $basePath = $this->basePath();

    $results = $this->results->getResults();
    foreach ($results as $singleResult):
        if ($singleResult->isPerson()) {
            $person_uniqueId = $singleResult->getUniqueID();
            $person_alternativeNames = $singleResult->getAlternativeNames();
            $person_biography = $singleResult->getBiography();
            $person_birthDate = $singleResult->getBirthDate();
            $person_birthPlace = $singleResult->getBirthPlace();
            $person_deathDate = $singleResult->getDeathDate();
            $person_deathPlace = $singleResult->getDeathPlace();
            $person_externalLinks = $singleResult->getPersonExternalLinks();
            $person_genre = $singleResult->getGenre();
            $person_influenced = $singleResult->getInfluenced();
            $person_influencedBy = $singleResult->getInfluencedBy();
            $person_movement = $singleResult->getMovement();
            $person_nameAsString = $singleResult->getNameAsString();
            $person_nationality = $singleResult->getNationality();
            $person_notableWork = $singleResult->getNotableWork();
            $person_occupation = $singleResult->getOccupation();
            $person_partner = $singleResult->getPartner();
            $person_pseudonym = $singleResult->getPseudonym();
            $person_spouse = $singleResult->getSpouse();
            $person_thumbnail = $singleResult->getThumbnail();
        } else
            $instances[] = $singleResult;
    endforeach;
    ?>
    <div class="knowledgeCard">
        <?=$this->render("elasticsearch/knowledgeCard.phtml")?>
    </div>
    <div class="container container-table-fix-md breadcrumbWrapper">
        <ul class="breadcrumb hidden-print">

            <li>
                <!-- Temporary solution  -->
                <a onclick="goBack()">Suche</a>
            </li>
            <!-- Example from swissbib classic
                <a href="/Search/Results?lookfor=malaria&type=AllFields">Suche: malaria</a>
            -->
            <li class="active">Personenseite: <? echo $person_nameAsString ?></li>
        </ul>
    </div>
    <?
    if (($person_nameAsString == "Nicht bekannt") || ($person_nameAsString == '')) {
    ?><h3><? echo "Oje, hier scheinen keine verlinkten Daten vorhanden zu sein!";?></h3>
    </br><button class="btn btn-primary" onclick="goBack()">Zurück</button>
    <? } else { ?>
    <!-- end class container container-table-fix-md breadcrumbWrapper -->
    <div class="container container-table-fix-md">
        <div class="row row-table-fix-md table-sidebar">
            <div class="col-md-12 col-table-fix-md dirty-hack-column">
                <div class="row bg-grey">
                    <div class="col-md-9 col-table-fix-md resultView bg-white">
                        <div class="results-top row">
                            <div class="col-md-12">
                                <!-- search results incl. icon
                                    <h1><i class="fa fa-search"></i> <span>Suchergebnisse</span></h1>
                                    <h2 class="visible-print-block">Ihre Suche: <span>malaria, 4048 Treffer</span></h2>
                                -->
                                <b>Springe zu:&nbsp;</b>
                                <a href="#works">B&uuml;cher &amp; Co. von <? echo $person_nameAsString ?></a>&nbsp;|&nbsp;
                                <a href="#authorsOfCommonWorks">Co-AutorInnen von <? echo $person_nameAsString ?></a>&nbsp;|&nbsp;
                                <a href="#worksOfAuthorsOfCommonWorks">B&uuml;cher &amp; Co. von <? echo $person_nameAsString ?>s Co-AutorInnen</a>&nbsp;|&nbsp;
                                <a href="#subjectsOfWorks">Mit <? echo $person_nameAsString ?> verwandte Themen</a>&nbsp;|&nbsp;
                                <a href="#worksWithSimilarSubjects">B&uuml;cher &amp; Co. mit ähnlichen Themen wie <? echo $person_nameAsString ?></a>&nbsp;|&nbsp;
                                <a href="#authorsOfWorksWithSimilarSubjects">AutorInnen von B&uuml;chern &amp; Co. mit ähnlichen Themen wie <? echo $person_nameAsString ?></a>
                            </div>
                            <!-- end class col-md-12 -->
                        </div>
                        <!-- end class results-top row -->
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-2">
                                    <h2></h2>
                                    <img class="img-responsive" src="<? echo $person_thumbnail ?>"
                                         alt="<? echo $person_thumbnail ?>">
                                </div>
                                <div class="col-sm-10">
                                    <div class="meta">
                                        <h2>
                                            <? echo $person_nameAsString ?>
                                        </h2>
                                    </div>
                                    <!-- occupation -->
                                    <div class="meta">
                                        <span><strong>Beruf/Tätigkeit: </strong></span><span><? echo $person_occupation ?></span>
                                    </div>
                                    <!-- birthdate, birthplace -->
                                    <div class="meta">
                                        <span><strong>Geboren: </strong></span><span><? echo $person_birthDate . ", " . $person_birthPlace ?></span><br>
                                    </div>
                                    <!-- deathdate, deathplace -->
                                    <div class="meta">
                                        <span><strong>Gestorben: </strong></span><span><? echo $person_deathDate . ", " . $person_deathPlace ?></span><br>
                                    </div>
                                    <!-- deathdate, deathplace -->
                                    <div class="meta">
                                        <span><strong>Nationalität: </strong></span><span><? echo $person_nationality ?></span><br><br>
                                    </div>
                                    <div id="accordion" class="panel-group" aria-multiselectable="true"
                                         role="tablist">
                                        <div id="holdings-details" class="panel panel-default">
                                            <div id="heading-details" class="panel-heading" role="tab">
                                                <h3 class="panel-title">
                                                    <a aria-expanded="false" href="#collapse-details"
                                                       data-toggle="collapse">
                                                        <span>Mehr Details zu <? echo $person_nameAsString ?></span>
                                                    </a>
                                                </h3>
                                            </div>
                                            <!-- end class panel-heading -->
                                        </div>
                                        <!-- end id holdings-details -->
                                    </div>
                                    <!-- end id accordion -->
                                </div>
                                <!-- end class col-sm-10 -->
                            </div>
                            <!-- end class row -->
                            <div id="collapse-details" class="panel-collapse collapse"
                                 aria-labelledby="heading-details" role="tabpanel" level="1">
                                <dl>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Biografie:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_biography ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Wichtigste Werke:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_notableWork ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Genre:</dt>
                                        <dd class="col-sm-10"><? echo $person_genre ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Epoche, Bewegung:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_movement ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Namens-<br>varianten:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_alternativeNames ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Pseudonyme:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_pseudonym ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>EhegattInnen:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_spouse ?></p></dd>
                                    </div>
                                    <!-- unclear what "partner" means
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>PartinerInnen:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_partner ?></p></dd>
                                    </div>
                                    -->
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Beeinflusst durch:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_influenced ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Beeinflusste:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_influencedBy ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Externe Websites:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $person_externalLinks ?></p></dd>
                                    </div>
                                </dl>
                            </div>
                            <!-- end id collapse-more -->
                        </div>
                        <!-- end class container-fluid -->

                        <!-- SEGMENT Werke -->
                        <?=$this->render("elasticsearch/resultsdetails.phtml")?>

                        <script>
                            var person_uniqueId = "<? echo $person_uniqueId?>";
                            var person_nameAsString = "<? echo $person_nameAsString ?>";
                            writeAuthordetailsModuleContentIntoHtml (person_uniqueId, person_nameAsString);
                        </script>
                        <?=$this->render("elasticsearch/ad_moduleGalleryAuthorsOfCommonWorks.phtml")?>
                        <?=$this->render("elasticsearch/ad_moduleCarouselWorksOfAuthorsOfCommonWorks.phtml")?>
                        <?=$this->render("elasticsearch/ad_moduleTagCloudSubjectsOfWorks.phtml")?>
                        <?=$this->render("elasticsearch/ad_moduleListWorksWithSimilarSubjects.phtml")?>
                        <?=$this->render("elasticsearch/ad_moduleGalleryAuthorsOfWorksWithSimilarSubjects.phtml")?>
                    </div>
                    <!-- end class col-md-9 col-table-fix-md resultView bg-white -->
                    <!-- sidebar -->
                    <?=$this->render("elasticsearch/sidebar.phtml")?>
                </div>
                <!-- end class row bg-grey -->
            </div>
            <!-- end class col-md-12 col-table-fix-md dirty-hack-column -->
        </div>
        <!-- end class row row-table-fix-md table-sidebar -->
    </div>
    <!-- container container-table-fix-md -->
    <? } ?>
    <div id="bottom-puffer"></div>
</div>
<!-- end class main -->
<!-- MODAL IN CASE WE NEED ONE -->
<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 id="modalTitle" class="modal-title"></h4>
            </div>
            <div class="modal-body">wird geladen......</div>
        </div>
    </div>
</div>
<!-- piwik analytics come here -->
<!-- #TODO: Do we need this?
<ul class="vakata-context"></ul><div style="display: none;" id="jstree-marker">&nbsp;</div>
-->
