<? echo "<div>UHE: " . __FILE__ . ", " . __LINE__ . "</div>"?>
<?php
//TODO: remove hardcoding
//This hardcoding is taken over from the original source (resultsdetails.phtml)
$resultsize=4048;
$actualpage=1;
$frompages=203;
?>
<div class="pagination-container hidden-print">
    <div class="hidden-sm hidden-xs">
        Treffer    <strong>1</strong> - <strong>20</strong>
        von <strong><?php $resultsize?></strong>
    </div>
    <!-- end class hidden-sm hidden-xs -->
    <div class="hidden-md hidden-lg">
        <strong><?php $resultsize?></strong> Treffer</div>
    <ul class="pagination">
        <li class="hidden-sm hidden-xs page">
            <a href="#">Seite:</a>
        </li>
        <li class="inactive"><a href="#"><i class="fa fa-caret-left"></i></a></li>
        <li class="page-numbers">
            <a>
                <span class="marked"><?php $actualpage?></span> von <span class="standard"><?php $frompages?></span>
            </a>
        </li>
        <li><a href="/Search/Results?lookfor=malaria&amp;type=AllFields&amp;page=2"><i class="fa fa-caret-right"></i></a></li>
    </ul>
</div>
<? echo "<div>UHE: " . __FILE__ . ", " . __LINE__ . "</div>"?>
