<!-- Knowledge Card-->
<div class="knowledgeCard">
    <script>
        $(function() {
            $( "#dialog" ).dialog({
                autoOpen: false,
                modal: true,
                responsive: true,
                height: 'auto',
                show: {
                    effect: "show",
                    duration: 1000
                },
                hide: {
                    effect: "hide",
                    duration: 1000
                }
            });

            function getValueIfAvailable (lookup, fallback) {
                if (typeof lookup !== 'undefined') {
                    if ($.isArray(lookup)) {
                        return lookup[0];
                    } else {
                        return lookup;
                    }
                } else {
                    return fallback;
                }
            }

            // get Dates; source priority as follows: dbpDate, schemaDate, dbpYear)
            function getDate (data, dbpDate, schemaDate, dbpYear) {

                var dates = data.person[0]._source;

                if ((dbpDate in dates)) {
                    var date = dates[dbpDate];
                } else if (schemaDate in dates) {
                    var date =  dates[schemaDate];
                } else if (dbpYear in dates) {
                    var date =  dates[dbpYear];
                } else {
                    var date =  'no content provided';
                }

                //check whether first character is a number or not
                var letter = isNaN(date[0]);

                //if the first character is a number
                if (letter == false) {
                    if (date.length >= 4) {
                        var kc_year = date.slice(0, 4);
                        //console.log(result);
                    } else {
                        var kc_year = kc_date;
                    }

                    if (date.length > 4) {
                        var kc_date = date.replace(/(\d{4})-(\d{1,2})-(\d{1,2})/, function(match,y,m,d) {
                            return d + '.' + m + '.' + y;
                        });
                    } else if (date.length == 4) {
                        var kc_date = date;
                    } else {
                        var kc_date = 'no content provided';
                    }
                // if the first character is not a number
                } else {
                    var kc_date = 'no content provided';
                    var kc_year = 'no content provided';
                }
                return [kc_date, kc_year];
                //console.log(result);
            }

            // get Values from array (comma separated output)
            function getValues (data, property) {

                var array = data.person[0]._source[property];

                if (typeof array !== 'undefined') {
                    if ($.isArray(array)) {
                        var result = "";
                        var fallbackResult = "";
                        for (var key in array) {
                            if (typeof array[key].de !== 'undefined') {
                                result += array[key].de + ", ";
                            } else if (typeof array[key].en !== 'undefined') {
                                fallbackResult += array[key].en + ", ";
                            }
                        }
                        var result = result.substring(0, result.length - 2);
                        var fallbackResult = fallbackResult.substring(0, fallbackResult.length - 2);
                    } else {
                        if (typeof array.de !== 'undefined') {
                            var result = array.de;
                        } else if (typeof array.en !== 'undefined') {
                            var fallbackResult = array.en;
                        }
                    }
                } else {
                    var result = 'no content provided';
                }

                if (!result) {
                    if (fallbackResult) {
                        var result = fallbackResult;
                    } else {
                        result = "no content provided";
                    }
                }
                return result;
                //console.log(result);
            }

            function getSubjects (data) {
                var array = data.bibliographicResource;
                if (typeof array !== 'undefined') {
                    if ($.isArray(array)) {
                        var result = "";
                        for (var key in array) {
                            result += array[key]._source['dct:subject'] + ",";
                            result = result.replace('undefined, ',' ');
                        }
                        var result = result.substring(0, result.length - 1);
                    }
                } else {
                    var result = "no content provided";
                }

                if (!result) {
                    result = "no content provided";
                } else {
                    result;
                }
                return result;
            }

            function getSubjectsPreferredName (data) {
                var array = data.DEFAULT;
                if (typeof array !== 'undefined') {
                    if ($.isArray(array)) {
                        var result = "";
                        for (var key in array) {
                            if (typeof array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheConferenceOrEvent'] != 'undefined') {
                                var literal = array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheConferenceOrEvent'][0]['@value'];
                            } else if (typeof array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheCorporateBody'] != "undefined") {
                                var literal = array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheCorporateBody'][0]['@value'];
                            } else if (typeof array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheFamily'] != "undefined") {
                                var literal = array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheFamily'][0]['@value'];
                            } else if (typeof array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForThePerson'] != "undefined") {
                                var literal = array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForThePerson'][0]['@value'];
                            } else if (typeof array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForThePlaceOrGeographicName'] != "undefined") {
                                var literal = array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForThePlaceOrGeographicName'][0]['@value'];
                            } else if (typeof array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheSubjectHeading'] != "undefined") {
                                var literal = array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheSubjectHeading'][0]['@value'];
                            } else if (typeof array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheWork'] != "undefined") {
                                var literal = array[key]._source['http://d-nb_info/standards/elementset/gnd#preferredNameForTheWork'][0]['@value'];
                            } else {
                                var literal = '';
                            }
                            result += literal + ", ";
                            result = result.replace('undefined, ', ' ');
                        }
                        var result = result.substring(0, result.length - 2);

                    }
                } else {
                    var result = "no content provided";
                }

                if (!result) {
                    result = "no content provided";
                } else {
                    result;
                }
                return result;
            }

            $("#dialog").dialog({width: $(window).width() * 0.9 });

            $(document).on('click', '.kcopener', function() {
                console.log("kcopener was clicked");

                var authorId = $(this).attr("authorid");
                var linkToAuthordetails = 'http://' + window.location.hostname +
                '/sbrd/Exploration/AuthorDetails?lookfor=' + authorId + '&type=AuthorForId#works';

                $.ajax({
                    url: "http://" + window.location.hostname +
                    "/sbrd/Ajax/Json?&method=getAuthorMulti&searcher=Elasticsearch",
                    type: "POST",
                    data: {"lookfor": authorId},
                    success: function (data) {
                    //kc_birthDate
                    var birthDates = getDate(data,'dbp:birthDate', 'schema:birthDate', 'dbp:birthYear');
                    var kc_birthDate = birthDates[0];
                    var kc_birthYear = birthDates[1];

                    var deathDates = getDate(data,'dbp:deathDate', 'schema:deathDate', 'dbp:deathYear');
                    var kc_deathDate = deathDates[0];
                    var kc_deathYear = deathDates[1];
                    var kc_birthPlace = getValues(data, 'lsb:dbpBirthPlaceAsLiteral');

                    var kc_deathPlace = getValues(data, 'lsb:dbpDeathPlaceAsLiteral');

                    var kc_nationality = getValues(data, 'lsb:dbpNationalityAsLiteral');

                    var kc_occupation = getValues(data, 'lsb:dbpOccupationAsLiteral');

                    var kc_subject = getSubjects(data);

                    var kc_thumbnail = getValueIfAvailable (data.person[0]._source['dbp:thumbnail'], "../themes/linkedswissbib/images/personAvatar.png");

                    //kc_names
                    var names = data.person[0]._source;

                    if (('foaf:lastName' in names) && ('foaf:firstName') in names) {
                        var kc_name = names['foaf:firstName'] + ' ' + names['foaf:lastName'];
                    } else if ('foaf:lastName' in names) {
                        var kc_name =  names['foaf:lastName'];
                    } else if ('foaf:name' in names) {
                        var kc_name =  names['foaf:name'];
                    } else {
                        var kc_name =  'no content provided';
                    }

                    //Contents KnowledgeCard
                    $('#kc_authorid').attr('href', linkToAuthordetails);
                    $('#kc_birthDate').text(kc_birthDate);
                    $('#kc_birthPlace').text(kc_birthPlace);
                    $('#kc_deathDate').text(kc_deathDate);
                    $('#kc_deathPlace').text(kc_deathPlace);
                    $('#kc_nationality').text(kc_nationality);
                    $('#kc_occupation').text(kc_occupation);
                    $('#kc_subject').text(kc_subject);
                    $('#kc_thumbnail').attr('src', kc_thumbnail);
                    $('#ui-id-1').text(kc_name + ' (' + kc_birthYear + ' - ' + kc_deathYear + ')'); //Title/Widget-Header

                    $( "#dialog" ).dialog( "open" );

                        $.ajax({
                            url: "http://" + window.location.hostname +
                            "/sbrd/Ajax/Json?&method=getSubjectMulti&searcher=Elasticsearch",
                            type: "POST",
                            data: {"lookfor": kc_subject},
                            success: function (result) {
                                // Zugriff auf JSON über "result"
                                //console.log(result);
                                var kc_subject = getSubjectsPreferredName(result);
                                console.log(kc_subject);
                                $('#kc_subject').text(kc_subject);
                            },
                            error: function (e) {
                                console.log(e);
                            }
                        });
                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
            });
        });

    </script>
    <div id="dialog" title="">
        <!-- SEGEMENT Header -->
        <div class="row">
            <div class="col-sm-3 col-md-2">
                <img class="img-responsive" id="kc_thumbnail" src= "" alt="kc_thumbnail">
            </div>
            <div class="col-sm-9">
                <!-- occupation -->
                <div class="meta">
                    <p id="kc_occupation"></p>
                </div>
                <!-- birthdate, birthplace -->
                <div class="meta">
                    <span><strong>Geboren: </strong></span><span id="kc_birthDate"></span>, <span id="kc_birthPlace"></span><br>
                </div>
                <!-- deathdate, deathplace -->
                <div class="meta">
                    <span><strong>Gestorben: </strong></span><span id="kc_deathDate"></span>, <span id="kc_deathPlace"><br>
                </div>
                <!-- deathdate, deathplace -->
                <div class="meta">
                    <span><strong>Nationalität: </strong></span><span id="kc_nationality"></span><br><br>
                </div>
                <!-- subject -->
                <div class="meta">
                    <span><strong>Themen/Schlagworte: </strong></span><span id="kc_subject"></span><br><br>
                </div>
            </div>
        </div>

        <!-- SEGMENT Literatur und Medien -->
        <!-- Carousel differs from authordetails.phtml in the following point:
        - Cover: style="min-height: 100px;
        - Cover: style="max-height: 100px;
        - Controls: style="max-height: 120px; max-width: 50px;
        - Book details: no "von"; no "Veröffentlicht"
        -->
        <div class="col-sm-12">
            <div class="results-top row">
                <h2>Literatur und Medien</h2>
            </div>
        </div>
        <!-- end class results-top row -->
        <div class="col-sm-12">
            <div class="row hidden-xs">
                <div data-ride="carousel" class="carousel slide" id="similar-items-carousel-knowledgeCard">

                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li class="active" data-slide-to="0" data-target="#similar-items-carousel-knowledgeCard"></li>
                        <li data-slide-to="1" data-target="#similar-items-carousel-knowledgeCard"></li>
                        <li data-slide-to="2" data-target="#similar-items-carousel-knowledgeCard"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <div class="row">
                                <div class="col-sm-3">
                                    <a href="/Record/32887101X" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Until you make the shore"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1908836679&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Until you make the shore</b>
                                            <!--
                                            <br>von: Conaway, Cameron
                                            <br>Veröffentlicht: 2014
                                            -->
                                        </div>
                                    </a>
                                </div>

                                <div class="col-sm-3">
                                    <a href="/Record/175208727" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Incarnadine : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1555976352&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Incarnadine : poems</b>
                                            <!--
                                            <br>von: Szybist, Mary
                                            <br>Veröffentlicht: 2013
                                            -->
                                        </div>
                                    </a>

                                </div>
                                <div class="col-sm-3">
                                    <a href="/Record/176525807" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Sightline : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=0976640554&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Sightline : poems</b>
                                            <!--
                                            <br>von: Austen, Elizabeth
                                            <br>Veröffentlicht: 2010
                                            -->
                                        </div>
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="/Record/314280111" class="hover-overlay"
                                       style="min-height: 100px">
                                        <img title="Start with a small guitar : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=0988924838&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Start with a small guitar : poems</b>
                                            <!--
                                            <br>von: Thompson, Lynne
                                            <br>Veröffentlicht: 2013
                                            -->
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="item">
                            <div class="row">
                                <div class="col-sm-3">
                                    <a href="/Record/327412496" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Copia : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1938160460&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Copia : poems</b>
                                            <br>von: Meitner, Erika
                                            <br>Veröffentlicht: 2014
                                        </div>
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="/Record/304901997" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Embark : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=0976640570&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Embark : poems</b>
                                            <br>Veröffentlicht: 2012
                                        </div>
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="/Record/307411990" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Collected poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1598530836&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Collected poems</b>
                                            <br>von: Cullen, Countee
                                            <br>Veröffentlicht: 2013
                                        </div>
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="/Record/331150034" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Streaming : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1566893755&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Streaming : poems</b>
                                            <br>von: Coke, Allison Adelle Hedge
                                            <br>Veröffentlicht: 2014
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="item">
                            <div class="row">
                                <div class="col-sm-3">
                                    <a href="/Record/335357466" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Selfish : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1555977081&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Selfish : poems</b>
                                            <br>von: Goldbarth, Albert
                                            <br>Veröffentlicht: 2015
                                        </div>
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="/Record/182619362" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Rumors of Earth : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1890193348&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Rumors of Earth : poems</b>
                                            <br>von: Edwards, Robert
                                            <br>Veröffentlicht: 2011
                                        </div>
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="/Record/318749041" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="The earth avails : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1555976662&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>The earth avails : poems</b>
                                            <br>von: Wunderlich, Mark
                                            <br>Veröffentlicht: 2014
                                        </div>
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="/Record/185321690" class="hover-overlay"
                                       style="min-height: 100px;">
                                        <img title="Must a violence : poems"
                                             src="https://resources.swissbib.ch/Cover/Show?isn=1609381297&amp;size=large"
                                             style="max-height: 100px;">

                                        <div class="content">
                                            <i title="Buch" class="fa fa-x fa-buch"></i>
                                            <b>Must a violence : poems</b>
                                            <br>von: Buchanan, Oni
                                            <br>Veröffentlicht: 2012
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end class carousel-inner -->
                    <!-- Controls -->
                    <a data-slide="prev" role="button" href="#similar-items-carousel-knowledgeCard"
                       class="left carousel-control" style="max-height: 120px; max-width: 50px;">
                        <span class="fa fa-chevron-left glyphicon-chevron-left" style="max-height: 100px;"></span>
                    </a>
                    <a data-slide="next" role="button" href="#similar-items-carousel-knowledgeCard"
                       class="right carousel-control" style="max-height: 120px; max-width: 50px;">
                        <span class="fa fa-chevron-right glyphicon-chevron-right" style="max-height: 100px;"></span>
                    </a>

                </div>
                <!-- end class carousel slide -->
            </div>
            <!-- end row -->
        </div>
        <!-- end col-sm-12 -->
        <div class="col-sm-12">
            <div class="row">
                <p><br><a id="kc_authorid" href="">» Mehr Literatur und Medien finden...</a></p>
            </div>
        </div>

        <!-- SEGEMENT Literatur und Medien finden in... -->
        <div class="col-sm-12">
            <div class="row">
            <h2>Literatur und Medien finden in...</h2>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="row">
            <span><a href="#">ALLE KATALOGE</a> | <a href="#">CATALOGUE1</a> | <a href="#">CATALOGUE2</a> | <a href="#">CATALOGUE3</a></span>
            </div>
        </div>
    </div>
    <!-- end id dialog -->
</div>
<!-- end id knowledgeCard -->


