<?
$instances = array();
$basePath = $this->basePath();
$results = $this->results->getResults();
foreach ($results as $singleResult):
    if ($singleResult->isPerson()) {
        $person_uniqueId = $singleResult->getUniqueID();
    } elseif ($singleResult->isSubject()) {
        $subject_uniqueId = $singleResult->getUniqueID();
    } else
        $instances[] = $singleResult;
endforeach;
?>

<!-- SEGMENT Werke -->
<div id="works" class="results-top row">
    <h2>Literatur und Medien</h2>
</div>
<!-- end class results-top row -->
<div id="tabs">
    <div class="row">
        <ul class="recordTabs nav nav-tabs">
            <li><a href="#tabs-1">Alles (4'048)</a></li>
            <li><a href="#tabs-2">Beteiligt an (560)</a></li>
            <li><a href="#tabs-3">Thema in (63)</a></li>
        </ul>
    </div>

    <div id="tabs-1">
        <div class="tab-pane">
            <div class="hidden-print search-controls clearfix row">
                <div class="col-lg-6 col-md-7 col-sm-7">
                    <div class="pagination-container hidden-print">
                        <div class="hidden-sm hidden-xs">
                            Treffer    <strong>1</strong> - <strong>20</strong>
                            von <strong>4'048</strong>
                        </div>
                        <!-- end class hidden-sm hidden-xs -->
                        <div class="hidden-md hidden-lg">
                            <strong>4'048</strong> Treffer</div>
                        <ul class="pagination">
                            <li class="hidden-sm hidden-xs page">
                                <a href="#">Seite:</a>
                            </li>
                            <li class="inactive"><a href="#"><i class="fa fa-caret-left"></i></a></li>
                            <li class="page-numbers">
                                <a>
                                    <span class="marked">1</span> von <span class="standard">203</span>
                                </a>
                            </li>
                            <li><a href="/Search/Results?lookfor=malaria&amp;type=AllFields&amp;page=2"><i class="fa fa-caret-right"></i></a></li>
                        </ul>
                    </div>
                    <!-- end class hidden-md hidden-lg -->
                </div>
                <!-- end class col-lg-6 col-md-7 col-sm-7 -->
                <div class="col-lg-6 col-md-5 col-sm-5 text-right">
                    <form class="form-inline" action="<?= $basePath ?>/Search/Results" method="get" name="sort">
                        <input name="lookfor" value="malaria" type="hidden"><input name="type" value="AllFields" type="hidden">    <input name="sortControlElement" value="sortControlElement" type="hidden">
                        <label for="sort_options_1">Sortieren nach</label>
                        <select id="sort_options_1" name="sort" class="jumpMenu form-control">
                            <option value="relevance" selected="selected">Relevanz</option>
                            <option value="publishDateSort desc">Jahr (neuestes zuerst)</option>
                            <option value="publishDateSort asc">Jahr (ältestes zuerst)</option>
                            <option value="author_sort asc">Autor (A-Z)</option>
                            <option value="author_sort desc">Autor (Z-A)</option>
                            <option value="title_sort asc">Titel (A-Z)</option>
                            <option value="title_sort desc">Titel (Z-A)</option>
                        </select>
                        <noscript><input type="submit" class="btn btn-default" value="Suchen" /></noscript>
                    </form>
                    <form class="form-inline" action="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields" method="post">
                        <input name="limitControlElement" value="limitControlElement" type="hidden">
                        <label for="limit">Treffer pro Seite</label>
                        <select id="limit" name="limit" class="jumpMenu form-control">
                            <option value="5">5</option>
                            <option value="10">10</option>
                            <option value="20" selected="selected">20</option>
                            <option value="40">40</option>
                            <option value="60">60</option>
                            <option value="80">80</option>
                            <option value="100">100</option>
                        </select>
                        <noscript><input type="submit" value="Suchen" /></noscript>
                    </form>
                    <div class="view-buttons hidden-xs">
                    </div>
                </div>
                <!-- end class col-lg-6 col-md-5 col-sm-5 text-right -->
            </div>
            <!-- end class hidden-print search-controls clearfix row -->
            <?
            foreach ($instances as $instance):
            $author = $instance->getName();
            $coverImage = $instance->getCover();
            $edition = $instance->getEdition();
            $format = $instance->getRdfType();
            $holdingInstitution = "ETH Zürich - Bibliothek HDB";
            $linkToHoldings = "#";
            $linkToOtherEditions ="#";
            $numberOfInstitutions = "2 Bibliotheken";
            $publicationStatement = $instance->getPublicationStatement();
            $statementOfResponsibility =  $instance->getStatementOfResponsibility();
            $title =  $instance->getTitle();
            $year = $instance->getYear();
            {
            ?>
            <!-- start result list form-->
            <form class="form-inline" method="post" name="bulkActionForm" action="/Cart/Home">
                <div id="#" class="row result clearfix">
                    <div class="col-xs-11 gutter-1">
                        <!--
                        <input value="330861492" class="hiddenId" type="hidden">
                        <input value="VuFind" class="hiddenSource" type="hidden">
                        -->
                        <!-- image -->
                        <div class="hidden-xs col-sm-3 col-md-2 no-gutter hidden-print">
                            <a href="<? echo $coverImage ?>" class="img-responsive">
                                <img alt="" class="recordcover" src=<? echo $coverImage ?>>
                            </a>
                        </div>
                        <!-- end class hidden-xs col-sm-3 col-md-2 no-gutter hidden-print -->
                        <!-- Kurztitel (vorher class="col-xs-7 col-sm-8 col-md-7" -->
                        <div class="col-xs-10 col-sm-8 col-md-7">
                            <div>
                                <h2>
                                    <a href="#" class="title singleLinkForBulk" title="<?echo $title ?>"><?echo $title ?></a>
                                </h2>
                            </div>
                            <!-- Untertitel und Verfasserangabe -->
                            <div class="meta">
                                <span id="subtitle"><? echo $statementOfResponsibility ?></span><br>
                                <span class="hidden-xs label"><strong>Verfasser/Beitragende:</strong></span><span class="authoruris"><? echo $author ?></span><br>
                            </div> <!-- Attribut einfügen -->
                            <!-- end class meta -->
                            <!-- Zeitschriftentitel, Erscheinungsjahr -->
                            <div class="meta">
                                <span class="hidden-xs label"><strong>Jahr:</strong></span><span><? echo $year ?></span><br>
                            </div>
                            <!-- end class meta -->
                            <!-- Ausgabe -->
                            <div class="meta">
                                <span class="hidden-xs label"><strong>Ausgabe:</strong></span><span><? echo $edition ?></span><br>
                            </div>
                            <!-- end class meta -->
                            <!-- ID #TODO: Why do we need this?
                            <div class="meta visible-print-block">
                                <span class="hidden-xs label"><strong>ID:</strong></span>
                                <span>330861492</span><br>
                            </div>
                            -->
                            <!-- end class meta visible-print-block -->
                            <!-- Medien-Typ -->
                            <div class="meta">
                                <span class="hidden-xs label"><strong>Format:</strong></span><span><? echo $format ?><!--<span class="iconlabel bk020000">Buch  </span> --></span><br>
                            </div>
                            <!-- end class meta -->
                        </div>
                        <!-- end class col-xs-10 col-sm-8 col-md-7 -->
                        <div class="col-xs-1 col-md-3 actions">
                            <div>
                                <a class="btn btn-primary dropdown-toggle hidden-print" id="dropdownLibraries" data-toggle="dropdown">
                                    <span><i class="fa fa-institution"></i></span>
                                    <span class="hidden-xs hidden-sm"><? echo $numberOfInstitutions ?></span>
                                </a>
                                <span class="visible-print-inline"><i class="fa fa-institution"></i></span>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownLibraries">
                                    <li role="presentation">
                                        <a role="menuitem" href="<? echo $linkToHoldings ?>">
                                            <span class="a-before"></span><? echo $holdingInstitution ?>
                                        </a>
                                    </li>
                                    <li role="presentation">
                                        <a role="menuitem" href="<? echo $linkToHoldings ?>">
                                            <span class="a-before"></span><? echo $holdingInstitution ?>
                                        </a>
                                    </li>
                                </ul>
                                <a class="btn btn-primary btn-frbr hidden-print" href="<? $linkToOtherEditions ?>" title="Weitere Ausgaben">
                                    <span><i class="fa fa-eye"></i></span>
                                    <span class="hidden-xs hidden-sm">Weitere Ausgaben</span>
                                </a>
                                <a class="btn btn-primary hidden-print" href="#" title="Zu Merkliste hinzufügen">
                                    <span class="memorizelistadd"><i class="fa fa-list-ul"></i></span>
                                    <span class="hidden-xs hidden-sm">Merkliste</span>
                                </a>
                                <div class="savedLists alert alert-info hidden hidden-xs hidden-sm hidden-print">
                                    <strong>Gespeichert in:</strong>
                                </div>
                            </div>
                        </div>
                        <!-- end class col-xs-1 col-md-3 actions -->
                        <!-- COINS #TODO: Why do we need this?
                        <span class="Z3988 hidden-print" title="ctx_ver=Z39.88-2004&amp;ctx_enc=info%3Aofi%2Fenc%3AUTF-8&amp;rfr_id=info%3Asid%2Fbaselbern.swissbib.ch%3Agenerator&amp;rft.title=Malaria+%3A+poems&amp;rft.date=2014&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Malaria+%3A+poems&amp;rft.au=Conaway%2C+Cameron&amp;rft.place=East+Lansing%2C+Mich&amp;rft.pub=Michigan+State+University+Press&amp;rft.edition=&amp;rft.isbn=1611861446"></span>
                        -->
                    </div>
                    <!-- end class col-xs-11 gutter-1 -->
                </div>
                <!-- end class row result clearfix -->
                <?
                }
                endforeach;
                ?>
                <div class="pagination-container hidden-print">
                    <ul class="pagination">
                        <li class="hidden-sm hidden-xs page">
                            <a href="#">Seite:</a>
                        </li>
                        <li class="inactive"><a href="#"><i class="fa fa-caret-left"></i></a></li>
                        <li class="page-numbers"><a><span class="marked">1</span> von <span class="standard">203</span></a>
                        </li>
                        <li><a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;page=2"><i class="fa fa-caret-right"></i></a></li>
                    </ul>
                </div>
                <!-- end class pagination-container hidden-print -->
            </form>
            <!-- end result list form-->
        </div>
        <!-- end class tabContent -->
    </div>
    <!-- end id tabs-1 -->
    <div id="tabs-2">
        <div class="tab-pane">
            <br>Noch keine Inhalte <br>
        </div>
        <!-- end class tabContent -->
    </div>
    <!-- end id tabs-2 -->
    <div id="tabs-3">
        <div class="tab-pane">
            <br>Noch keine Inhalte <br>
        </div>
        <!-- end class tabContent -->
    </div>
    <!-- end id tabs-3 -->
</div>
<!-- end div tabs -->
<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>