
<p>&nbsp;</p>
<h1> powered by fuzzy linked data - Hopp Chur!</h1>

<?
    $results = $this->results->getResults();
    foreach ($results as $rdfDriver): ?>
        <div>
            <a href="<?= $rdfDriver->getUniqueID()?>">document-IRI</a>
        </div>
        <div>
            <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getRdf()); ?>
        </div>
            <div>&nbsp;</div>
    <?endforeach;?>

<p>&nbsp;</p>