<!-- start sidebar -->
<div style="" class="sidebar col-md-3 col-table-fix-md hidden-print resultView">
    <h4>FAQ</h4>
    <?
    $results = $this->results->getResults();
    foreach ($results as $singleResult):
        if ($singleResult->isPerson()) { ?>
            <!-- FAQ1 for authordetails -->
        <ul class="list-group" id="side-panel-faq1">
            <li class="list-group-item title" data-toggle="collapse" href="#side-collapse-faq1">
                Was ist eine Personenseite?
            </li>
            <div id="side-collapse-faq1" class="collapse in">
                <span  class="list-group-item facetAND">Die Personenseite enthält durch <a target="_blank" href="https://de.wikipedia.org/wiki/Linked_Open_Data"><i class="fa fa-external-link"></i> Linked Open Data (LOD)</a> angereichterte Angaben zu Personen, welche als VerfasserInnen  oder Beitragende in den Medien von swissbib aufgeführt werden. Als Datenquellen zur Anreicherung werden die <a target="_blank" href="http://wiki.dbpedia.org/"><i class="fa fa-external-link"></i> DBpedia</a>, die <a target="_blank" href="http://www.dnb.de/DE/Standardisierung/GND/gnd_node.html"><i class="fa fa-external-link"></i> GND</a> sowie <a target="_blank" href="http://viaf.org/"><i class="fa fa-external-link"></i> VIAF</a>  genutzt.</span>
            </div>
            <!-- end class collapse in -->
        </ul>
        <? } elseif($singleResult->isSubject()) { ?>
            <!-- FAQ1 for subjectdetails -->
            <ul class="list-group" id="side-panel-faq1">
                <li class="list-group-item title" data-toggle="collapse" href="#side-collapse-faq1">
                    Was ist eine Themenseite?
                </li>
                <div id="side-collapse-faq1" class="collapse in">
                    <span  class="list-group-item facetAND">Die Themenseite enthält durch <a target="_blank" href="https://de.wikipedia.org/wiki/Linked_Open_Data"><i class="fa fa-external-link"></i> Linked Open Data (LOD)</a> angereichterte Angaben zu Themen, welche als Schlagworte in den Medien von swissbib aufgeführt werden. Als Datenquelle zur Anreicherung wird die <a target="_blank" href="http://www.dnb.de/DE/Standardisierung/GND/gnd_node.html"><i class="fa fa-external-link"></i> Gemeinsame Normadatei (GND)</a> der Deutschen Nationalbibliothek genutzt.</span>
                </div>
                <!-- end class collapse in -->
            </ul>
        <?}
    endforeach;
    ?>

    <ul class="list-group" id="side-panel-faq2">
        <li class="list-group-item title" data-toggle="collapse"
            href="#side-collapse-faq2">
            FAQ2
        </li>
        <div id="side-collapse-faq2" class="collapse in">
            <span  class="list-group-item facetAND">FAQ2</span>
        </div>
        <!-- end class collapse in -->
    </ul>
</div>
<!-- end sidebar -->