<div role="main" class="main">
    <script src="../themes/linkedswissbib/js/authordetails.js"></script>
    <script src="../themes/linkedswissbib/js/detailspages.js"></script>
    <?
    $instances = array();
    $basePath = $this->basePath();
    $results = $this->results->getResults();
    foreach ($results as $singleResult):
        if ($singleResult->isSubject()) {
            //GND Ontology: http://d-nb.info/standards/elementset/gnd
            $subject_alternativeNames = $singleResult->getSubjectAlternativeNames(); //http://d-nb_info/standards/elementset/gnd#variantNameForTheSubjectHeading --> more variants available!
            $subject_uriForBroaderTerms = $singleResult->getSubjectUriForBroaderTerms(); //http://d-nb_info/standards/elementset/gnd#broaderTermGeneral   http://d-nb.info/standards/elementset/gnd#broaderTermGeneric   http://d-nb_info/standards/elementset/gnd#broaderTermInstantial  http://d-nb_info/standards/elementset/gnd#broaderTermPartitive
            $subject_ddc = $singleResult->getSubjectDDC(); //http://d-nb.info/standards/elementset/gnd#relatedDdcWithDegreeOfDeterminacy1/2/3/4 --> DDC-Notation Related Dewey Decimal Classification with degree of determinacy 1/2/3/4
            $subject_definition = $singleResult->getSubjectDefinition(); //http://d-nb_info/standards/elementset/gnd#definition --> Erläuterungen
            $subject_externalLinks = $singleResult->getSubjectExternalLinks();
            $subject_gndSubjectCategory = $singleResult->getSubjectGndSubjectCategory(); //http://d-nb.info/standards/elementset/gnd#gndSubjectCategory --> GND Systematik
            $subject_uriForNarrowerTerms = $singleResult->getSubjectUriForNarrowerTerms(); //http://d-nb.info/standards/elementset/gnd#narrowerTermGeneral  http://d-nb.info/standards/elementset/gnd#narrowerTermGeneric	http://d-nb.info/standards/elementset/gnd#narrowerTermInstantial  http://d-nb.info/standards/elementset/gnd#narrowerTermPartitive
            $subject_preferredName = $singleResult->getSubjectPreferredName();
            $subject_uriForRelatedTerms = $singleResult->getSubjectUriForRelatedTerms(); //http://d-nb_info/standards/elementset/gnd#relatedTerm
            $subject_thumbnail = $singleResult->getSubjectThumbnail(); //returns only dummy image
            $subject_uniqueId = $singleResult->getUniqueID();
        } else
            $instances[] = $singleResult;
    endforeach;
    ?>
    <script>
        var gndIds_subject_relatedTerms = "<? echo $subject_uriForRelatedTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_relatedTerms, "#subject_relatedTerms");

        var gndIds_subject_broaderTerms = "<? echo $subject_uriForBroaderTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_broaderTerms, "#subject_broaderTerms");

        var gndIds_subject_narrowerTerms = "<? echo $subject_uriForNarrowerTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_narrowerTerms, "#subject_narrowerTerms");
    </script>
    <div class="container container-table-fix-md breadcrumbWrapper">
        <ul class="breadcrumb hidden-print">

            <li>
                <a href=" <?= $basePath ?>/Exploration/SubjectDetails?lookfor=<? echo $subject_uniqueId ?>&amp;type=SubjectById">Suche</a>
            </li>
            <!-- Example from swissbib classic
                <a href="/Search/Results?lookfor=malaria&type=AllFields">Suche: malaria</a>
            -->
            <li class="active"><a
                    href="<?= $basePath ?>/Exploration/SubjectDetails?lookfor=<? echo $subject_uniqueId ?>&amp;type=SubjectById"><? echo $subject_uniqueId ?></a>
            </li>
            <li class="active">Themenseite</li>
            <?

            ?>
        </ul>
    </div>
    <!-- end class container container-table-fix-md breadcrumbWrapper -->
    <div class="container container-table-fix-md">
        <div class="row row-table-fix-md table-sidebar">
            <div class="col-md-12 col-table-fix-md dirty-hack-column">
                <div class="row bg-grey">
                    <div class="col-md-9 col-table-fix-md resultView bg-white">
                        <div class="results-top row">
                            <div class="col-md-9">
                                <!-- search results incl. icon
                                    <h1><i class="fa fa-search"></i> <span>Suchergebnisse</span></h1>
                                    <h2 class="visible-print-block">Ihre Suche: <span>malaria, 4048 Treffer</span></h2>
                                -->
                                <b>Springe zu:&nbsp;</b>
                                <a href="#works">Literatur und Medien</a>&nbsp;|&nbsp;
                                <a href="#mediaType">Medientyp</a>&nbsp;|&nbsp;
                                <a href="#authorsOfWorksWithSubject">Autoren und Beitragende von Literatur und Medien mit diesem Thema</a>&nbsp;|&nbsp;
                                <a href="#worksWithSimilarSubjects">Literatur und Medien von Autoren mit ähnlichen Werken</a>&nbsp;|&nbsp;
                                <a href="#worksOfAuthorsWithWorksWithSubject">Literatur und Medien von Autoren mit ähnlichen Themen</a>&nbsp;|&nbsp;
                            </div>
                            <!-- end class col-md-9 -->
                            <div class="col-md-3">
                                <!-- icons export, save etc. -->
                                <div class="searchtools">
                                    <div class="searchtools hidden-print">
                                        <!-- #TODO: Replace static links -->
                                        <a href="<?= $basePath ?>?lookfor=malaria&amp;type=AllFields&amp;view=rss"
                                           title="Neue Einträge zu dieser Suche per Feed gemeldet bekommen"><i
                                                class="fa fa-rss"></i></a>
                                        <a href="<?= $basePath ?>/Search/Email" id="mailSearch29097239" title="Per E-Mail versenden"><i
                                                class="fa fa-envelope"></i></a>
                                        <a href="<?= $basePath ?>/MyResearch/SaveSearch?save=29097239" title="Suche speichern"><i
                                                class="fa fa-plus-square"></i></a>
                                        <!-- Styling & Funktionstests -->
                                        <a class="export-toggle dropdown-toggle hidden-xs hidden-sm"
                                           data-toggle="dropdown" href="<?= $basePath ?>/Record//Export" title=" Exportieren"><i
                                                class="fa fa-share"></i></a>
                                        <ul class="dropdown-menu" role="export-menu">
                                            <li class="visible-md visible-lg">
                                                <a href="<?= $basePath ?>/doExport?f=EndNote">Exportieren
                                                    nach EndNote</a>
                                            </li>
                                            <li class="visible-md visible-lg">
                                                <a href="<?= $basePath ?>/Cart/doExport?f=BibTeX">Exportieren
                                                    nach BibTeX</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <!-- end class searchtools hidden-print -->
                                </div>
                                <!-- end class searchtools -->
                            </div>
                            <!-- end class col-md-3 -->
                        </div>
                        <!-- end class results-top row -->
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-2">
                                    <h2></h2>
                                    <img class="img-responsive" src="<? echo $subject_thumbnail ?>"
                                         alt="<? echo $person_thumbnail ?>">
                                </div>
                                <div class="col-sm-10">
                                    <div class="meta">
                                        <h2>
                                            <? echo $subject_preferredName ?>
                                        </h2>
                                        <div class="knowledgeCard">
                                        <?=$this->render("elasticsearch/knowledgeCardAuthor.phtml")?>
                                        </div>
                                    </div>
                                    <!-- name variants -->
                                    <div class="meta">
                                        <span><strong>Namensvarianten: </strong></span><span><? echo $subject_alternativeNames ?></span><br>
                                    </div>
                                    <!-- Themengebiet GND-Systematik -->
                                    <div class="meta">
                                        <span><strong>Themengebiet (GND): </strong></span><span><? echo $subject_gndSubjectCategory ?></span><br><br>
                                    </div>
                                    <div id="accordion" class="panel-group" aria-multiselectable="true"
                                         role="tablist">
                                        <div id="holdings-details" class="panel panel-default">
                                            <div id="heading-details" class="panel-heading" role="tab">
                                                <h3 class="panel-title">
                                                    <a aria-expanded="false" href="#collapse-details"
                                                       data-toggle="collapse">
                                                        <span>Mehr Details zu <? echo $subject_preferredName ?></span>
                                                    </a>
                                                </h3>
                                            </div>
                                            <!-- end class panel-heading -->
                                        </div>
                                        <!-- end id holdings-details -->
                                    </div>
                                    <!-- end id accordion -->
                                </div>
                                <!-- end class col-sm-10 -->
                            </div>
                            <!-- end class row -->
                            <div id="collapse-details" class="panel-collapse collapse"
                                 aria-labelledby="heading-details" role="tabpanel" level="1">
                                <dl>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- description -->
                                        <p>Erläuterungen:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_definition; ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- broader Terms -->
                                        <p>Übergeordnete Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_broaderTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- narrower Terms -->
                                        <p>Untergeordnete Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_narrowerTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Verwandte Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_relatedTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- Dewey Decimal Classification -->
                                        <p>Dewey Decimal <br> Classification (Notation):</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_ddc ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- external Links und sources -->
                                        <p>Externe Websites:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_externalLinks ?></p></dd>
                                    </div>
                                </dl>
                            </div>
                            <!-- end id collapse-more -->
                        </div>
                        <!-- end class container-fluid -->
                        <!-- SEGMENT Werke -->
                        <?=$this->render("elasticsearch/resultsdetails.phtml")?>

                        <!-- SEGMENT Medientyp -->
                        <div id="mediaType" class="results-top row">
                            <h2>Medientypen</h2>
                        </div>
                        <!-- end class results-top row -->
                        <div class="row">
                            <ul class="list-inline">
                                <li>
                                    <a href="#">
                                        <figure>
                                            <img class="img-responsive"
                                                 src="../themes/linkedswissbib/images/icon_hoerbuch.jpg" alt="Hörbuch">
                                            <figcaption>Hörbuch / Tonaufnahme (5'601)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <figure>
                                            <img src="../themes/linkedswissbib/images/icon_noten.jpg" alt="Noten">
                                            <figcaption>Noten (Partitur) (650)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <figure>
                                            <img src="../themes/linkedswissbib/images/icon_eBook.jpg" alt="eBook">
                                            <figcaption>eBook (1'256)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <figure>
                                            <img src="../themes/linkedswissbib/images/icon_buch.jpg" alt="Buch">
                                            <figcaption>gedrucktes Buch (34'455)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <figure style="vertical-align: top;">
                                            <img style="vertical-align: top;"
                                                 src="../themes/linkedswissbib/images/icon_video.jpg" alt="video">
                                            <figcaption>Film / Video (4'756)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- end class row -->

                        <!-- SEGMENT Autoren mit ähnlichen Themen -->
                        <!-- id="relatedSubjects" -->
                        <script>
                            var subject_uniqueId = "<? echo $subject_uniqueId?>";
                            writeSubjectdetailsModuleContentIntoHtml (subject_uniqueId);
                        </script>
                        <?=$this->render("elasticsearch/sd_moduleGalleryAuthorsOfWorksWithSubjects.phtml")?>
                        <?=$this->render("elasticsearch/sd_moduleCarouselWorksWithSimilarSubjects.phtml")?>
                        <?=$this->render("elasticsearch/sd_moduleListWorksOfAuthorsWithWorksWithSubject.phtml")?>
                    </div>
                    <!-- end class col-md-9 col-table-fix-md resultView bg-white -->
                    <!-- sidebar -->
                    <?=$this->render("elasticsearch/sidebar.phtml")?>
                </div>
                <!-- end class row bg-grey -->
            </div>
            <!-- end class col-md-12 col-table-fix-md dirty-hack-column -->
        </div>
        <!-- end class row row-table-fix-md table-sidebar -->
    </div>
    <!-- container container-table-fix-md -->
    <div id="bottom-puffer"></div>
</div>
<!-- end class main -->
<!-- MODAL IN CASE WE NEED ONE -->
<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 id="modalTitle" class="modal-title"></h4>
            </div>
            <div class="modal-body">wird geladen......</div>
        </div>
    </div>
</div>
<!-- piwik analytics come here -->
<!-- #TODO: Do we need this?
<ul class="vakata-context"></ul><div style="display: none;" id="jstree-marker">&nbsp;</div>
-->
