<div role="main" class="main">
    <script src="../themes/linkedswissbib/js/authordetails.js"></script>
    <script src="../themes/linkedswissbib/js/getterdetails.js"></script>
    <?
    $instances = array();
    $basePath = $this->basePath();
    $results = $this->results->getResults();
    foreach ($results as $singleResult):
        if ($singleResult->isSubject()) {
            //GND Ontology: http://d-nb.info/standards/elementset/gnd
            $subject_alternativeNames = $singleResult->getSubjectAlternativeNames(); //http://d-nb_info/standards/elementset/gnd#variantNameForTheSubjectHeading --> more variants available!
            $subject_broaderTerms = $singleResult->getSubjectBroaderTerms(); //http://d-nb_info/standards/elementset/gnd#broaderTermGeneral   http://d-nb.info/standards/elementset/gnd#broaderTermGeneric   http://d-nb_info/standards/elementset/gnd#broaderTermInstantial  http://d-nb_info/standards/elementset/gnd#broaderTermPartitive
            $subject_ddc1 = $singleResult->getSubjectDDC1(); //http://d-nb.info/standards/elementset/gnd#relatedDdcWithDegreeOfDeterminacy1 --> DDC-Notation Related Dewey Decimal Classification with degree of determinacy 1
            $subject_ddc2 = $singleResult->getSubjectDDC2(); //http://d-nb.info/standards/elementset/gnd#relatedDdcWithDegreeOfDeterminacy2 --> DDC-Notation Related Dewey Decimal Classification with degree of determinacy 2
            $subject_ddc3 = $singleResult->getSubjectDDC3(); //http://d-nb.info/standards/elementset/gnd#relatedDdcWithDegreeOfDeterminacy3 --> DDC-Notation Related Dewey Decimal Classification with degree of determinacy 3
            $subject_ddc4 = $singleResult->getSubjectDDC4(); //http://d-nb.info/standards/elementset/gnd#relatedDdcWithDegreeOfDeterminacy4 --> DDC-Notation Related Dewey Decimal Classification with degree of determinacy 4
            $subject_definition = $singleResult->getSubjectDefinition(); //http://d-nb_info/standards/elementset/gnd#definition --> Erläuterungen
            $subject_externalLinkSkos = $singleResult->getSubjectExternalLinkSkos(); //skos:exactMatch, foaf:page
            $subject_externalLinkFoafPage = $singleResult->getSubjectExternalLinkFoafPage(); //skos:exactMatch, foaf:pag
            $subject_gndSubjectCategory = $singleResult->getSubjectGndSubjectCategory(); //http://d-nb.info/standards/elementset/gnd#gndSubjectCategory --> GND Systematik
            $subject_narrowerTerms = $singleResult->getSubjectNarrowerTerms(); //http://d-nb.info/standards/elementset/gnd#narrowerTermGeneral  http://d-nb.info/standards/elementset/gnd#narrowerTermGeneric	http://d-nb.info/standards/elementset/gnd#narrowerTermInstantial  http://d-nb.info/standards/elementset/gnd#narrowerTermPartitive
            $subject_preferredName = $singleResult->getSubjectPreferredName();
            $subject_relatedTerms = $singleResult->getSubjectRelatedTerms(); //http://d-nb_info/standards/elementset/gnd#relatedTerm
            $subject_thumbnail = $singleResult->getSubjectThumbnail(); //returns only dummy image
            $subject_uniqueId = $singleResult->getUniqueID();
        } else
            $instances[] = $singleResult;
    endforeach;
    ?>
    <script>
        var gndIds_subject_relatedTerms = "<? echo $subject_relatedTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_relatedTerms, "#subject_relatedTerms");

        var gndIds_subject_broaderTerms = "<? echo $subject_broaderTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_broaderTerms, "#subject_broaderTerms");

        var gndIds_subject_narrowerTerms = "<? echo $subject_narrowerTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_narrowerTerms, "#subject_narrowerTerms");
    </script>
    <div class="container container-table-fix-md breadcrumbWrapper">
        <ul class="breadcrumb hidden-print">

            <li>
                <a href=" <?= $basePath ?>/Exploration/SubjectDetails?lookfor=<? echo $subject_uniqueId ?>&amp;type=SubjectById">Suche</a>
            </li>
            <!-- Example from swissbib classic
                <a href="/Search/Results?lookfor=malaria&type=AllFields">Suche: malaria</a>
            -->
            <li class="active"><a
                    href="<?= $basePath ?>/Exploration/SubjectDetails?lookfor=<? echo $subject_uniqueId ?>&amp;type=SubjectById"><? echo $subject_uniqueId ?></a>
            </li>
            <li class="active">Themenseite</li>
            <?

            ?>
        </ul>
    </div>
    <!-- end class container container-table-fix-md breadcrumbWrapper -->
    <div class="container container-table-fix-md">
        <div class="row row-table-fix-md table-sidebar">
            <div class="col-md-12 col-table-fix-md dirty-hack-column">
                <div class="row bg-grey">
                    <div class="col-md-9 col-table-fix-md resultView bg-white">
                        <div class="results-top row">
                            <div class="col-md-9">
                                <!-- search results incl. icon
                                    <h1><i class="fa fa-search"></i> <span>Suchergebnisse</span></h1>
                                    <h2 class="visible-print-block">Ihre Suche: <span>malaria, 4048 Treffer</span></h2>
                                -->
                                <b>Springe zu:&nbsp;</b>
                                <a href="#works">Literatur und Medien</a>&nbsp;|&nbsp;
                                <a href="#gallery">Galerie</a>&nbsp;|&nbsp;
                                <a href="#relatedSubjects">Ähnliche Themen</a>&nbsp;|&nbsp;
                            </div>
                            <!-- end class col-md-9 -->
                            <div class="col-md-3">
                                <!-- icons export, save etc. -->
                                <div class="searchtools">
                                    <div class="searchtools hidden-print">
                                        <!-- #TODO: Replace static links -->
                                        <a href="<?= $basePath ?>?lookfor=malaria&amp;type=AllFields&amp;view=rss"
                                           title="Neue Einträge zu dieser Suche per Feed gemeldet bekommen"><i
                                                class="fa fa-rss"></i></a>
                                        <a href="<?= $basePath ?>/Search/Email" id="mailSearch29097239" title="Per E-Mail versenden"><i
                                                class="fa fa-envelope"></i></a>
                                        <a href="<?= $basePath ?>/MyResearch/SaveSearch?save=29097239" title="Suche speichern"><i
                                                class="fa fa-plus-square"></i></a>
                                        <!-- Styling & Funktionstests -->
                                        <a class="export-toggle dropdown-toggle hidden-xs hidden-sm"
                                           data-toggle="dropdown" href="<?= $basePath ?>/Record//Export" title=" Exportieren"><i
                                                class="fa fa-share"></i></a>
                                        <ul class="dropdown-menu" role="export-menu">
                                            <li class="visible-md visible-lg">
                                                <a href="<?= $basePath ?>/doExport?f=EndNote">Exportieren
                                                    nach EndNote</a>
                                            </li>
                                            <li class="visible-md visible-lg">
                                                <a href="<?= $basePath ?>/Cart/doExport?f=BibTeX">Exportieren
                                                    nach BibTeX</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <!-- end class searchtools hidden-print -->
                                </div>
                                <!-- end class searchtools -->
                            </div>
                            <!-- end class col-md-3 -->
                        </div>
                        <!-- end class results-top row -->
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-2">
                                    <h2></h2>
                                    <img class="img-responsive" src="<? echo $subject_thumbnail ?>"
                                         alt="<? echo $person_thumbnail ?>">
                                </div>
                                <div class="col-sm-10">
                                    <div class="meta">
                                        <h2>
                                            <? echo $subject_preferredName ?>
                                        </h2>
                                        <div class="knowledgeCard">
                                        <?=$this->render("elasticsearch/knowledgeCardAuthor.phtml")?>
                                        </div>
                                    </div>
                                    <!-- name variants -->
                                    <div class="meta">
                                        <span><strong>Namensvarianten: </strong></span><span><? echo $subject_alternativeNames ?></span><br>
                                    </div>
                                    <!-- Themengebiet GND-Systematik -->
                                    <div class="meta">
                                        <span><strong>Themengebiet (GND): </strong></span><span><? echo $subject_gndSubjectCategory ?></span><br><br>
                                    </div>
                                    <div id="accordion" class="panel-group" aria-multiselectable="true"
                                         role="tablist">
                                        <div id="holdings-details" class="panel panel-default">
                                            <div id="heading-details" class="panel-heading" role="tab">
                                                <h3 class="panel-title">
                                                    <a aria-expanded="false" href="#collapse-details"
                                                       data-toggle="collapse">
                                                        <span>Mehr Details zu <? echo $subject_preferredName ?></span>
                                                    </a>
                                                </h3>
                                            </div>
                                            <!-- end class panel-heading -->
                                        </div>
                                        <!-- end id holdings-details -->
                                    </div>
                                    <!-- end id accordion -->
                                </div>
                                <!-- end class col-sm-10 -->
                            </div>
                            <!-- end class row -->
                            <div id="collapse-details" class="panel-collapse collapse"
                                 aria-labelledby="heading-details" role="tabpanel" level="1">
                                <dl>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- description -->
                                        <p>Erläuterungen:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_definition; ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- broader Terms -->
                                        <p>Übergeordnete Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_broaderTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- narrower Terms -->
                                        <p>Untergeordnete Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_narrowerTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Verwandte Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_relatedTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- Dewey Decimal Classification -->
                                        <p>Dewey Decimal <br> Classification (Notation):</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_ddc1 . "<br>" . $subject_ddc2 . "<br>" . $subject_ddc3 . "<br>" . $subject_ddc4 ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- external Links und sources -->
                                        <p>Externe Links:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_uniqueId . "<br>" . $subject_externalLinkSkos . "<br>" . $subject_externalLinkFoafPage ?></p></dd>
                                    </div>
                                </dl>
                            </div>
                            <!-- end id collapse-more -->
                        </div>
                        <!-- end class container-fluid -->
                        <!-- SEGMENT Werke -->
                        <?=$this->render("elasticsearch/resultsdetails.phtml")?>

                        <!-- SEGMENT Medientyp -->
                        <div id="mediaType" class="results-top row">
                            <h2>Medientypen</h2>
                        </div>
                        <!-- end class results-top row -->
                        <div class="row">
                            <ul class="list-inline">
                                <li>
                                    <a href="#">
                                        <figure>
                                            <img class="img-responsive"
                                                 src="../themes/linkedswissbib/images/icon_hoerbuch.jpg" alt="Hörbuch">
                                            <figcaption>Hörbuch / Tonaufnahme (5'601)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <figure>
                                            <img src="../themes/linkedswissbib/images/icon_noten.jpg" alt="Noten">
                                            <figcaption>Noten (Partitur) (650)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <figure>
                                            <img src="../themes/linkedswissbib/images/icon_eBook.jpg" alt="eBook">
                                            <figcaption>eBook (1'256)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <figure>
                                            <img src="../themes/linkedswissbib/images/icon_buch.jpg" alt="Buch">
                                            <figcaption>gedrucktes Buch (34'455)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <figure style="vertical-align: top;">
                                            <img style="vertical-align: top;"
                                                 src="../themes/linkedswissbib/images/icon_video.jpg" alt="video">
                                            <figcaption>Film / Video (4'756)<br></figcaption>
                                        </figure>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- end class row -->
                        
                        <!-- SEGMENT Autoren mit ähnlichen Themen -->
                        <!-- id="relatedSubjects" -->
                        <?=$this->render("elasticsearch/similarAuthors.phtml")?>

                    </div>
                    <!-- end class col-md-9 col-table-fix-md resultView bg-white -->

                    <!-- start sidebar -->
                    <div style="" class="sidebar col-md-3 col-table-fix-md hidden-print resultView">
                        <h4>Suche verfeinern</h4>
                        <!--
                          MyLibraries (swissbib jargon 'Favoriten' are implemented as Solr-QueryFacets
                          They are going to be merged with the usual Term-FacetList placed in the SideFacets component of VF2
                          Because we use institutions as additional facets beside 'Favoriten'  but 'Favoriten' are queried against the institution index in Solr too
                          I added an additional mylibrary index field which enables us to merge both groups in one list in the SideFacets Component
                          One alternative could be to map the field names on the level of the application (complicated configuration, error prone and complicated for
                          others to work with it. Another alternative to could be to use a separated template only for these facets (and to duplicate code) which isn't really nice also
                        -->
                        <!-- start filter Bibliotheksverbund -->
                        <ul class="list-group" id="side-panel-union">
                            <li class="list-group-item title" data-toggle="collapse" href="#side-collapse-union">
                                Bibliotheksverbund
                            </li>
                            <div id="side-collapse-union" class="collapse in">
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=union%3A%22IDS%22"
                                   class="list-group-item facetAND">
                                    <span class="badge">2'759</span>Informationsverbund Deutschschweiz
                                </a>
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=union%3A%22IDSBB%22"
                                   class="list-group-item facetAND">
                                    <span class="badge">1'591</span> IDS Basel Bern</a>
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=union%3A%22NEBIS%22"
                                   class="list-group-item facetAND">
                                    <span class="badge">1'480</span>NEBIS</a>
                                <a id="more-narrowGroupHidden-union" class="list-group-item"
                                   href="javascript:moreFacets('narrowGroupHidden-union')">mehr ...</a>
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=union%3A%22RE81%22"
                                   class="list-group-item facetAND narrowGroupHidden-union hidden">
                                    <span class="badge">306</span>RERO Vaud
                                </a>
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=union%3A%22IDSLU%22"
                                   class="list-group-item facetAND narrowGroupHidden-union hidden">
                                    <span class="badge">228</span>IDS Luzern
                                </a>
                                <a class="list-group-item narrowGroupHidden-union hidden"
                                   href="javascript:lessFacets('narrowGroupHidden-union')">weniger ...</a>
                            </div>
                            <!-- end class collapse in -->
                        </ul>
                        <!-- end filter Bibliotheksverbund -->
                        <!-- end filter Verfasser/Beitreagende -->
                        <ul class="list-group" id="side-panel-navAuthor_full">
                            <li class="list-group-item title" data-toggle="collapse"
                                href="#side-collapse-navAuthor_full">
                                Verfasser/Beitragende
                            </li>
                            <div id="side-collapse-navAuthor_full" class="collapse in">
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=navAuthor_full%3A%22Tanner%2C+Marcel%22"
                                   class="list-group-item facetAND">
                                    <span class="badge">121</span>Tanner, Marcel
                                </a>
                                <a id="more-narrowGroupHidden-navAuthor_full" class="list-group-item"
                                   href="javascript:moreFacets('narrowGroupHidden-navAuthor_full')">mehr ...</a>
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=navAuthor_full%3A%22Lengeler%2C+Christian%22"
                                   class="list-group-item facetAND narrowGroupHidden-navAuthor_full hidden">
                                    <span class="badge">44</span>Lengeler, Christian
                                </a>
                                <a class="list-group-item narrowGroupHidden-format hidden"
                                   href="javascript:lessFacets('narrowGroupHidden-format')">weniger ...</a>
                            </div>
                            <!-- end class collapse in -->
                        </ul>
                        <!-- end filter Verfasser/Beitreagende -->
                        <!-- start filter Sprache -->
                        <ul class="list-group" id="side-panel-language">
                            <li class="list-group-item title" data-toggle="collapse" href="#side-collapse-language">
                                Sprache
                            </li>
                            <div id="side-collapse-language" class="collapse in">
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=language%3A%22eng%22"
                                   class="list-group-item facetAND">
                                    <span class="badge">2'602</span>Englisch
                                </a>
                                <a id="more-narrowGroupHidden-language" class="list-group-item"
                                   href="javascript:moreFacets('narrowGroupHidden-language')">mehr ...</a>
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=language%3A%22dut%22"
                                   class="list-group-item facetAND narrowGroupHidden-language hidden">
                                    <span class="badge">20</span>Niederländisch
                                </a>
                                <a class="list-group-item narrowGroupHidden-language hidden"
                                   href="javascript:lessFacets('narrowGroupHidden-language')">weniger ...</a>
                            </div>
                            <!-- end class collapse in -->
                        </ul>
                        <!-- end filter Sprache -->
                        <!-- start filter Thema -->
                        <ul class="list-group" id="side-panel-navSub_green">
                            <li class="list-group-item title" data-toggle="collapse" href="#side-collapse-navSub_green">
                                Thema
                            </li>
                            <div id="side-collapse-navSub_green" class="collapse in">
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=navSub_green%3A%22Malaria%22"
                                   class="list-group-item facetAND">
                                    <span class="badge">344</span>Malaria
                                </a>
                                <a id="more-narrowGroupHidden-navSub_green" class="list-group-item"
                                   href="javascript:moreFacets('narrowGroupHidden-navSub_green')">mehr ...</a>
                                <a href="<?= $basePath ?>/Search/Results?lookfor=malaria&amp;type=AllFields&amp;filter%5B%5D=navSub_green%3A%22Medizin%22"
                                   class="list-group-item facetAND narrowGroupHidden-navSub_green hidden">
                                    <span class="badge">47</span>Medizin</a>
                                <a class="list-group-item narrowGroupHidden-navSubform hidden"
                                   href="javascript:lessFacets('narrowGroupHidden-navSubform')">weniger ...</a>
                            </div>
                            <!-- end class collapse in -->
                        </ul>
                        <!-- end filter Thema -->
                        <ul class="list-group" id="side-panel-publishDate">
                            <li class="list-group-item title" data-toggle="collapse" href="#side-collapse-publishDate">
                                Erscheinungsjahr
                            </li>
                            <div id="side-collapse-publishDate" class="collapse in">
                                <script type="text/javascript">
                                    //&lt;!--
                                    $(document).ready(function () {
                                        var fillTexts = function () {
                                            var v = publishDatedateSlider.getValue();
                                            $('#publishDatefrom').val(v[0]);
                                            $('#publishDateto').val(v[1]);
                                        };
                                        var publishDatedateSlider = $('#publishDatedateSlider')
                                            .slider({
                                                'min': 300,
                                                'max': 2017,
                                                'handle': "square",
                                                'tooltip': "hide",
                                                'value': [300, 2017]
                                            })
                                            .on('slide', fillTexts)
                                            .data('slider');
                                    });
                                    //--&gt;
                                </script>
                                <li class="list-group-item">
                                    <form action="" name="publishDateFilter" id="publishDateFilter">
                                        <input name="lookfor" value="malaria" type="hidden">
                                        <input name="type" value="AllFields" type="hidden">
                                        <input name="daterange[]" value="publishDate" type="hidden">

                                        <div class="row">
                                            <div class="col-sm-6">
                                                <label for="publishDatefrom">
                                                    Von:
                                                </label>
                                                <input maxlength="4" class="form-control" name="publishDatefrom"
                                                       id="publishDatefrom" value="" placeholder="300" type="text">
                                            </div>
                                            <div class="col-sm-6">
                                                <label for="publishDateto">
                                                    Bis:
                                                </label>
                                                <input maxlength="4" class="form-control" name="publishDateto"
                                                       id="publishDateto" value="" placeholder="2017" type="text">
                                            </div>
                                        </div>
                                        <div class="slider-container">
                                            <div id="" class="slider slider-horizontal">
                                                <div class="slider-track">
                                                    <div style="left: 0px; width: 0%;" class="slider-track-low"></div>
                                                    <div style="left: 0%; width: 100%;" class="slider-selection"></div>
                                                    <div style="right: 0px; width: 0%;" class="slider-track-high"></div>
                                                    <div tabindex="0" style="left: 0%;"
                                                         class="slider-handle min-slider-handle"></div>
                                                    <div tabindex="0" style="left: 100%;"
                                                         class="slider-handle max-slider-handle"></div>
                                                </div>
                                                <div style="left: 50%; margin-left: -41.5px;"
                                                     class="tooltip tooltip-main top hide">
                                                    <div class="tooltip-arrow"></div>
                                                    <div class="tooltip-inner">300 : 2017</div>
                                                </div>
                                                <div style="left: 0%; margin-left: -20px;"
                                                     class="tooltip tooltip-min top hide">
                                                    <div class="tooltip-arrow"></div>
                                                    <div class="tooltip-inner">300</div>
                                                </div>
                                                <div style="left: 100%; margin-left: -24px;"
                                                     class="tooltip tooltip-max top hide">
                                                    <div class="tooltip-arrow"></div>
                                                    <div class="tooltip-inner">2017</div>
                                                </div>
                                            </div>
                                            <input value="300,2017" data-value="300,2017" style="display: none;"
                                                   class="hidden" id="publishDatedateSlider" type="text">
                                        </div>
                                        <input class="btn btn-default" value="Suchen" type="submit">
                                    </form>
                                </li>
                            </div>
                            <!-- end class collapse in -->
                        </ul>
                    </div>
                    <!-- end sidebar -->
                </div>
                <!-- end class row bg-grey -->
            </div>
            <!-- end class col-md-12 col-table-fix-md dirty-hack-column -->
        </div>
        <!-- end class row row-table-fix-md table-sidebar -->
    </div>
    <!-- container container-table-fix-md -->
    <div id="bottom-puffer"></div>
</div>
<!-- end class main -->
<!-- MODAL IN CASE WE NEED ONE -->
<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 id="modalTitle" class="modal-title"></h4>
            </div>
            <div class="modal-body">wird geladen......</div>
        </div>
    </div>
</div>
<!-- piwik analytics come here -->
<!-- #TODO: Do we need this?
<ul class="vakata-context"></ul><div style="display: none;" id="jstree-marker">&nbsp;</div>
-->
