<div role="main" class="main">
    <?
	$this->headScript()->appendFile("authordetails.js");
	$this->headScript()->appendFile("detailspages.js");

	$instances = array();
    $basePath = $this->basePath();
    $results = $this->results->getResults();
    foreach ($results as $singleResult):
        if ($singleResult->isSubject()) {
            //GND Ontology: http://d-nb.info/standards/elementset/gnd
            $subject_alternativeNames = $singleResult->getSubjectAlternativeNames(); //http://d-nb_info/standards/elementset/gnd#variantNameForTheSubjectHeading --> more variants available!
            $subject_uriForBroaderTerms = $singleResult->getSubjectUriForBroaderTerms(); //http://d-nb_info/standards/elementset/gnd#broaderTermGeneral   http://d-nb.info/standards/elementset/gnd#broaderTermGeneric   http://d-nb_info/standards/elementset/gnd#broaderTermInstantial  http://d-nb_info/standards/elementset/gnd#broaderTermPartitive
            $subject_ddc = $singleResult->getSubjectDDC(); //http://d-nb.info/standards/elementset/gnd#relatedDdcWithDegreeOfDeterminacy1/2/3/4 --> DDC-Notation Related Dewey Decimal Classification with degree of determinacy 1/2/3/4
            $subject_definition = $singleResult->getSubjectDefinition(); //http://d-nb_info/standards/elementset/gnd#definition --> Erläuterungen
            $subject_externalLinks = $singleResult->getSubjectExternalLinks();
            $subject_gndSubjectCategory = $singleResult->getSubjectGndSubjectCategory(); //http://d-nb.info/standards/elementset/gnd#gndSubjectCategory --> GND Systematik
            $subject_uriForNarrowerTerms = $singleResult->getSubjectUriForNarrowerTerms(); //http://d-nb.info/standards/elementset/gnd#narrowerTermGeneral  http://d-nb.info/standards/elementset/gnd#narrowerTermGeneric	http://d-nb.info/standards/elementset/gnd#narrowerTermInstantial  http://d-nb.info/standards/elementset/gnd#narrowerTermPartitive
            $subject_preferredName = $singleResult->getSubjectPreferredName();
            $subject_uriForRelatedTerms = $singleResult->getSubjectUriForRelatedTerms(); //http://d-nb_info/standards/elementset/gnd#relatedTerm
            $subject_thumbnail = $singleResult->getSubjectThumbnail(); //returns only dummy image
            $subject_uniqueId = $singleResult->getUniqueID();
        } else
            $instances[] = $singleResult;
    endforeach;
    //Check if there are bibliographic resources about the subject
    if (count($instances) == 0) {
        $subject_availableInBibRes = "false";
    }
    ?>
    <script>
        var gndIds_subject_relatedTerms = "<? echo $subject_uriForRelatedTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_relatedTerms, "#subject_relatedTerms", "withKnowledgeCard");

        var gndIds_subject_broaderTerms = "<? echo $subject_uriForBroaderTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_broaderTerms, "#subject_broaderTerms", "withKnowledgeCard");

        var gndIds_subject_narrowerTerms = "<? echo $subject_uriForNarrowerTerms ?>";
        writeSubjectNamesIntoHtmlId(gndIds_subject_narrowerTerms, "#subject_narrowerTerms", "withKnowledgeCard");
    </script>
    <div class="container container-table-fix-md breadcrumbWrapper">
        <ul class="breadcrumb hidden-print">

            <li>
                <!-- Temporary solution  -->
                <a onclick="goBack()">Suche</a>
            </li>
            <!-- Example from swissbib classic
                <a href="/Search/Results?lookfor=malaria&type=AllFields">Suche: malaria</a>
            -->
            <li class="active">Themenseite: <? echo $subject_preferredName ?></li>
        </ul>

    </div>
    <?
    //Don't display subject details pages if there is no information about the subject or if there are no bibliographic resources about the subject
    if (($subject_preferredName == "Nicht bekannt") || ($subject_preferredName == '') || $subject_availableInBibRes == "false" ) {
    ?><h3><? echo "Oje, hier scheinen keine verlinkten Daten vorhanden zu sein!";?></h3>
    </br><button class="btn btn-primary" onclick="goBack()">Zurück</button>
    <? } else { ?>
    <!-- end class container container-table-fix-md breadcrumbWrapper -->
    <div class="container container-table-fix-md">
        <div class="row row-table-fix-md table-sidebar">
            <div class="col-md-12 col-table-fix-md dirty-hack-column">
                <div class="row bg-grey">
                    <div class="col-md-9 col-table-fix-md resultView bg-white">
                        <!-- end class results-top row -->
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-2">
                                    <h2></h2>
                                    <img class="img-responsive" src="<? echo $subject_thumbnail ?>"
                                         alt="<? echo $subject_thumbnail ?>">
                                </div>
                                <div class="col-sm-10">
                                    <div class="meta">
                                        <h2>
                                            <? echo $subject_preferredName ?>
                                        </h2>
                                    </div>
                                    <!-- name variants -->
                                    <div class="meta">
                                        <span><strong>Namensvarianten: </strong></span><span><? echo $subject_alternativeNames ?></span><br>
                                    </div><br>
                                    <div id="accordion" class="panel-group" aria-multiselectable="true"
                                         role="tablist">
                                        <div id="holdings-details" class="panel panel-default">
                                            <div id="heading-details" class="panel-heading" role="tab">
                                                <h3 class="panel-title">
                                                    <a aria-expanded="false" href="#collapse-details"
                                                       data-toggle="collapse">
                                                        <span>Mehr Details zu <? echo $subject_preferredName ?></span>
                                                    </a>
                                                </h3>
                                            </div>
                                            <!-- end class panel-heading -->
                                        </div>
                                        <!-- end id holdings-details -->
                                    </div>
                                    <!-- end id accordion -->
                                </div>
                                <!-- end class col-sm-10 -->
                            </div>
                            <!-- end class row -->
                            <div id="collapse-details" class="panel-collapse collapse"
                                 aria-labelledby="heading-details" role="tabpanel" level="1">
                                <dl>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- description -->
                                        <p>Erläuterungen:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_definition; ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- broader Terms -->
                                        <p>Übergeordnete Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_broaderTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- narrower Terms -->
                                        <p>Untergeordnete Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_narrowerTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <p>Verwandte Themen:</p></dt>
                                        <dd class="col-sm-10"><p id="subject_relatedTerms"></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- Dewey Decimal Classification -->
                                        <p>Dewey Decimal <br> Classification (Notation):</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_ddc ?> (Website zurzeit offline)</p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- Themengebiet GND-Systematik -->
                                        <p>Themengebiet (GND):</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_gndSubjectCategory ?></p></dd>
                                    </div>
                                    <div class="row">
                                        <dt class="col-sm-2">
                                        <!-- external Links und sources -->
                                        <p>Externe Websites:</p></dt>
                                        <dd class="col-sm-10"><p><? echo $subject_externalLinks ?></p></dd>
                                    </div>
                                </dl>
                            </div>
                            <!-- end id collapse-more -->
                        </div>
                        <!-- end class container-fluid -->
                        <div class="row"<p><strong>Springe zu:<strong></p></div>
                        <div class="row">
                            <a class="ui-button" style="margin-bottom: 5px;" href="#works">&darr; <strong>B&uuml;cher</strong> &amp; Co.</a>
                            <a class="ui-button" style="margin-bottom: 5px;" href="#authorsOfWorksWithSubject">&darr; <strong>AutorInnen</strong> zum Thema <? echo $subject_preferredName ?></a>
                            <a class="ui-button" style="margin-bottom: 5px;" href="#worksWithSimilarSubjects">&darr; <strong>B&uuml;cher</strong> &amp; Co. mit <strong>ähnlichen Themen</strong></a>
                            <a class="ui-button" style="margin-bottom: 5px;" href="#worksWithBroaderSubjects">&darr; <strong>B&uuml;cher</strong> &amp; Co. zu <strong>übergeordneten Themen</strong></a>
                            <a class="ui-button" style="margin-bottom: 5px;" href="#worksWithNarrowerSubjects">&darr; <strong>B&uuml;cher</strong> Co. zu <strong>untergeordneten Themen</strong></a>
                        </div>

                        <!-- SEGMENT Werke -->
                        <?=$this->render("elasticsearch/resultsdetails.phtml")?>

                        <!-- SEGMENT Autoren mit ähnlichen Themen -->
                        <!-- id="relatedSubjects" -->
                        <script>
                            var subject_uniqueId = "<? echo $subject_uniqueId?>";
                            var subject_preferredNameAsString = "<? echo $subject_preferredName ?>";
                            var gndIds_subject_broaderTerms = "<? echo $subject_uriForBroaderTerms ?>";
                            var gndIds_subject_narrowerTerms = "<? echo $subject_uriForNarrowerTerms ?>";
                            writeSubjectdetailsModuleContentIntoHtml (subject_uniqueId, subject_preferredNameAsString, gndIds_subject_broaderTerms, gndIds_subject_narrowerTerms);
                        </script>
                        <?=$this->render("elasticsearch/sd_moduleGalleryAuthorsOfWorksWithSubjects.phtml")?>
                        <?=$this->render("elasticsearch/sd_moduleCarouselWorksWithSimilarSubjects.phtml")?>
                        <?=$this->render("elasticsearch/sd_moduleListWorksWithBroaderSubjects.phtml")?>
                        <?=$this->render("elasticsearch/sd_moduleListWorksWithNarrowerSubjects.phtml")?>
                    </div>
                    <!-- end class col-md-9 col-table-fix-md resultView bg-white -->
                    <!-- sidebar -->
                    <?=$this->render("elasticsearch/sidebar.phtml")?>
                </div>
                <!-- end class row bg-grey -->
            </div>
            <!-- end class col-md-12 col-table-fix-md dirty-hack-column -->
        </div>
        <!-- end class row row-table-fix-md table-sidebar -->
    </div>
    <? } ?>
    <!-- container container-table-fix-md -->
    <div id="bottom-puffer"></div>
</div>
<div class="knowledgeCard">
    <?=$this->render("elasticsearch/knowledgeCard.phtml")?>
</div>
<!-- end class main -->
<!-- MODAL IN CASE WE NEED ONE -->
<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 id="modalTitle" class="modal-title"></h4>
            </div>
            <div class="modal-body">wird geladen......</div>
        </div>
    </div>
</div>
<!-- piwik analytics come here -->
<!-- #TODO: Do we need this?
<ul class="vakata-context"></ul><div style="display: none;" id="jstree-marker">&nbsp;</div>
-->
